# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class Information(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, status=None, affected=None, message=None):  # noqa: E501
        """Information - a model defined in OpenAPI

        :param status: The status of this Information.  # noqa: E501
        :type status: int
        :param affected: The affected of this Information.  # noqa: E501
        :type affected: int
        :param message: The message of this Information.  # noqa: E501
        :type message: str
        """
        self.openapi_types = {
            'status': int,
            'affected': int,
            'message': str
        }

        self.attribute_map = {
            'status': 'status',
            'affected': 'affected',
            'message': 'message'
        }

        self._status = status
        self._affected = affected
        self._message = message

    @classmethod
    def from_dict(cls, dikt) -> 'Information':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Information of this Information.  # noqa: E501
        :rtype: Information
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self):
        """Gets the status of this Information.


        :return: The status of this Information.
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Information.


        :param status: The status of this Information.
        :type status: int
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def affected(self):
        """Gets the affected of this Information.


        :return: The affected of this Information.
        :rtype: int
        """
        return self._affected

    @affected.setter
    def affected(self, affected):
        """Sets the affected of this Information.


        :param affected: The affected of this Information.
        :type affected: int
        """
        if affected is None:
            raise ValueError("Invalid value for `affected`, must not be `None`")  # noqa: E501

        self._affected = affected

    @property
    def message(self):
        """Gets the message of this Information.


        :return: The message of this Information.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this Information.


        :param message: The message of this Information.
        :type message: str
        """
        if message is None:
            raise ValueError("Invalid value for `message`, must not be `None`")  # noqa: E501

        self._message = message
