# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
from api import util


class Login(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, username=None, password=None, device_id=None, device_name=None):  # noqa: E501
        """Login - a model defined in OpenAPI

        :param username: The username of this Login.  # noqa: E501
        :type username: str
        :param password: The password of this Login.  # noqa: E501
        :type password: str
        :param device_id: The device_id of this Login.  # noqa: E501
        :type device_id: str
        :param device_name: The device_name of this Login.  # noqa: E501
        :type device_name: str
        """
        self.openapi_types = {
            'username': str,
            'password': str,
            'device_id': str,
            'device_name': str
        }

        self.attribute_map = {
            'username': 'username',
            'password': 'password',
            'device_id': 'deviceId',
            'device_name': 'deviceName'
        }

        self._username = username
        self._password = password
        self._device_id = device_id
        self._device_name = device_name

    @classmethod
    def from_dict(cls, dikt) -> 'Login':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Login of this Login.  # noqa: E501
        :rtype: Login
        """
        return util.deserialize_model(dikt, cls)

    @property
    def username(self):
        """Gets the username of this Login.


        :return: The username of this Login.
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this Login.


        :param username: The username of this Login.
        :type username: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501
        if username is not None and len(username) < 1:
            raise ValueError("Invalid value for `username`, length must be greater than or equal to `1`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this Login.


        :return: The password of this Login.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this Login.


        :param password: The password of this Login.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501
        if password is not None and len(password) < 1:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `1`")  # noqa: E501

        self._password = password

    @property
    def device_id(self):
        """Gets the device_id of this Login.


        :return: The device_id of this Login.
        :rtype: str
        """
        return self._device_id

    @device_id.setter
    def device_id(self, device_id):
        """Sets the device_id of this Login.


        :param device_id: The device_id of this Login.
        :type device_id: str
        """
        if device_id is not None and len(device_id) < 1:
            raise ValueError("Invalid value for `device_id`, length must be greater than or equal to `1`")  # noqa: E501

        self._device_id = device_id

    @property
    def device_name(self):
        """Gets the device_name of this Login.


        :return: The device_name of this Login.
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name):
        """Sets the device_name of this Login.


        :param device_name: The device_name of this Login.
        :type device_name: str
        """
        if device_name is not None and len(device_name) < 1:
            raise ValueError("Invalid value for `device_name`, length must be greater than or equal to `1`")  # noqa: E501

        self._device_name = device_name
