# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
import re
from api import util

import re  # noqa: E501

class MethodParam(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pipeline_id=None, method_id=None, method_param_def_id=None, data_type=None, name=None, value=None):  # noqa: E501
        """MethodParam - a model defined in OpenAPI

        :param pipeline_id: The pipeline_id of this MethodParam.  # noqa: E501
        :type pipeline_id: int
        :param method_id: The method_id of this MethodParam.  # noqa: E501
        :type method_id: int
        :param method_param_def_id: The method_param_def_id of this MethodParam.  # noqa: E501
        :type method_param_def_id: int
        :param data_type: The data_type of this MethodParam.  # noqa: E501
        :type data_type: str
        :param name: The name of this MethodParam.  # noqa: E501
        :type name: str
        :param value: The value of this MethodParam.  # noqa: E501
        :type value: str
        """
        self.openapi_types = {
            'pipeline_id': int,
            'method_id': int,
            'method_param_def_id': int,
            'data_type': str,
            'name': str,
            'value': str
        }

        self.attribute_map = {
            'pipeline_id': 'PipelineID',
            'method_id': 'MethodID',
            'method_param_def_id': 'MethodParamDefID',
            'data_type': 'DataType',
            'name': 'Name',
            'value': 'Value'
        }

        self._pipeline_id = pipeline_id
        self._method_id = method_id
        self._method_param_def_id = method_param_def_id
        self._data_type = data_type
        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'MethodParam':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MethodParam of this MethodParam.  # noqa: E501
        :rtype: MethodParam
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pipeline_id(self):
        """Gets the pipeline_id of this MethodParam.

        none  # noqa: E501

        :return: The pipeline_id of this MethodParam.
        :rtype: int
        """
        return self._pipeline_id

    @pipeline_id.setter
    def pipeline_id(self, pipeline_id):
        """Sets the pipeline_id of this MethodParam.

        none  # noqa: E501

        :param pipeline_id: The pipeline_id of this MethodParam.
        :type pipeline_id: int
        """
        if pipeline_id is None:
            raise ValueError("Invalid value for `pipeline_id`, must not be `None`")  # noqa: E501

        self._pipeline_id = pipeline_id

    @property
    def method_id(self):
        """Gets the method_id of this MethodParam.

        none  # noqa: E501

        :return: The method_id of this MethodParam.
        :rtype: int
        """
        return self._method_id

    @method_id.setter
    def method_id(self, method_id):
        """Sets the method_id of this MethodParam.

        none  # noqa: E501

        :param method_id: The method_id of this MethodParam.
        :type method_id: int
        """
        if method_id is None:
            raise ValueError("Invalid value for `method_id`, must not be `None`")  # noqa: E501

        self._method_id = method_id

    @property
    def method_param_def_id(self):
        """Gets the method_param_def_id of this MethodParam.

        none  # noqa: E501

        :return: The method_param_def_id of this MethodParam.
        :rtype: int
        """
        return self._method_param_def_id

    @method_param_def_id.setter
    def method_param_def_id(self, method_param_def_id):
        """Sets the method_param_def_id of this MethodParam.

        none  # noqa: E501

        :param method_param_def_id: The method_param_def_id of this MethodParam.
        :type method_param_def_id: int
        """

        self._method_param_def_id = method_param_def_id

    @property
    def data_type(self):
        """Gets the data_type of this MethodParam.

        none  # noqa: E501

        :return: The data_type of this MethodParam.
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this MethodParam.

        none  # noqa: E501

        :param data_type: The data_type of this MethodParam.
        :type data_type: str
        """
        if data_type is not None and not re.search(r'^.{0,6}', data_type):  # noqa: E501
            raise ValueError("Invalid value for `data_type`, must be a follow pattern or equal to `/^.{0,6}/`")  # noqa: E501

        self._data_type = data_type

    @property
    def name(self):
        """Gets the name of this MethodParam.

        none  # noqa: E501

        :return: The name of this MethodParam.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MethodParam.

        none  # noqa: E501

        :param name: The name of this MethodParam.
        :type name: str
        """
        if name is not None and not re.search(r'^.{0,30}', name):  # noqa: E501
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^.{0,30}/`")  # noqa: E501

        self._name = name

    @property
    def value(self):
        """Gets the value of this MethodParam.

        none  # noqa: E501

        :return: The value of this MethodParam.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this MethodParam.

        none  # noqa: E501

        :param value: The value of this MethodParam.
        :type value: str
        """
        if value is not None and not re.search(r'^.{0,30}', value):  # noqa: E501
            raise ValueError("Invalid value for `value`, must be a follow pattern or equal to `/^.{0,30}/`")  # noqa: E501

        self._value = value
