# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
import re
from api import util

import re  # noqa: E501

class PipelineParam(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, pipeline_id=None, pipeline_param_def_id=None, data_type=None, name=None, value=None):  # noqa: E501
        """PipelineParam - a model defined in OpenAPI

        :param pipeline_id: The pipeline_id of this PipelineParam.  # noqa: E501
        :type pipeline_id: int
        :param pipeline_param_def_id: The pipeline_param_def_id of this PipelineParam.  # noqa: E501
        :type pipeline_param_def_id: int
        :param data_type: The data_type of this PipelineParam.  # noqa: E501
        :type data_type: str
        :param name: The name of this PipelineParam.  # noqa: E501
        :type name: str
        :param value: The value of this PipelineParam.  # noqa: E501
        :type value: str
        """
        self.openapi_types = {
            'pipeline_id': int,
            'pipeline_param_def_id': int,
            'data_type': str,
            'name': str,
            'value': str
        }

        self.attribute_map = {
            'pipeline_id': 'PipelineID',
            'pipeline_param_def_id': 'PipelineParamDefID',
            'data_type': 'DataType',
            'name': 'Name',
            'value': 'Value'
        }

        self._pipeline_id = pipeline_id
        self._pipeline_param_def_id = pipeline_param_def_id
        self._data_type = data_type
        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'PipelineParam':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PipelineParam of this PipelineParam.  # noqa: E501
        :rtype: PipelineParam
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pipeline_id(self):
        """Gets the pipeline_id of this PipelineParam.

        none  # noqa: E501

        :return: The pipeline_id of this PipelineParam.
        :rtype: int
        """
        return self._pipeline_id

    @pipeline_id.setter
    def pipeline_id(self, pipeline_id):
        """Sets the pipeline_id of this PipelineParam.

        none  # noqa: E501

        :param pipeline_id: The pipeline_id of this PipelineParam.
        :type pipeline_id: int
        """
        if pipeline_id is None:
            raise ValueError("Invalid value for `pipeline_id`, must not be `None`")  # noqa: E501

        self._pipeline_id = pipeline_id

    @property
    def pipeline_param_def_id(self):
        """Gets the pipeline_param_def_id of this PipelineParam.

        none  # noqa: E501

        :return: The pipeline_param_def_id of this PipelineParam.
        :rtype: int
        """
        return self._pipeline_param_def_id

    @pipeline_param_def_id.setter
    def pipeline_param_def_id(self, pipeline_param_def_id):
        """Sets the pipeline_param_def_id of this PipelineParam.

        none  # noqa: E501

        :param pipeline_param_def_id: The pipeline_param_def_id of this PipelineParam.
        :type pipeline_param_def_id: int
        """

        self._pipeline_param_def_id = pipeline_param_def_id

    @property
    def data_type(self):
        """Gets the data_type of this PipelineParam.

        none  # noqa: E501

        :return: The data_type of this PipelineParam.
        :rtype: str
        """
        return self._data_type

    @data_type.setter
    def data_type(self, data_type):
        """Sets the data_type of this PipelineParam.

        none  # noqa: E501

        :param data_type: The data_type of this PipelineParam.
        :type data_type: str
        """
        if data_type is not None and not re.search(r'^.{0,6}', data_type):  # noqa: E501
            raise ValueError("Invalid value for `data_type`, must be a follow pattern or equal to `/^.{0,6}/`")  # noqa: E501

        self._data_type = data_type

    @property
    def name(self):
        """Gets the name of this PipelineParam.

        none  # noqa: E501

        :return: The name of this PipelineParam.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PipelineParam.

        none  # noqa: E501

        :param name: The name of this PipelineParam.
        :type name: str
        """
        if name is not None and not re.search(r'^.{0,30}', name):  # noqa: E501
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^.{0,30}/`")  # noqa: E501

        self._name = name

    @property
    def value(self):
        """Gets the value of this PipelineParam.

        none  # noqa: E501

        :return: The value of this PipelineParam.
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this PipelineParam.

        none  # noqa: E501

        :param value: The value of this PipelineParam.
        :type value: str
        """
        if value is not None and not re.search(r'^.{0,30}', value):  # noqa: E501
            raise ValueError("Invalid value for `value`, must be a follow pattern or equal to `/^.{0,30}/`")  # noqa: E501

        self._value = value
