# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from api.models.base_model_ import Model
import re
from api import util

import re  # noqa: E501

class Trend(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, trend_group_id=None, trend_def_id=None, time_exponent=None, format=None, unit_id=None, color=None, axis_label=None):  # noqa: E501
        """Trend - a model defined in OpenAPI

        :param id: The id of this Trend.  # noqa: E501
        :type id: int
        :param name: The name of this Trend.  # noqa: E501
        :type name: str
        :param trend_group_id: The trend_group_id of this Trend.  # noqa: E501
        :type trend_group_id: int
        :param trend_def_id: The trend_def_id of this Trend.  # noqa: E501
        :type trend_def_id: str
        :param time_exponent: The time_exponent of this Trend.  # noqa: E501
        :type time_exponent: int
        :param format: The format of this Trend.  # noqa: E501
        :type format: str
        :param unit_id: The unit_id of this Trend.  # noqa: E501
        :type unit_id: str
        :param color: The color of this Trend.  # noqa: E501
        :type color: str
        :param axis_label: The axis_label of this Trend.  # noqa: E501
        :type axis_label: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'trend_group_id': int,
            'trend_def_id': str,
            'time_exponent': int,
            'format': str,
            'unit_id': str,
            'color': str,
            'axis_label': str
        }

        self.attribute_map = {
            'id': 'ID',
            'name': 'Name',
            'trend_group_id': 'TrendGroupID',
            'trend_def_id': 'TrendDefID',
            'time_exponent': 'TimeExponent',
            'format': 'Format',
            'unit_id': 'UnitID',
            'color': 'Color',
            'axis_label': 'AxisLabel'
        }

        self._id = id
        self._name = name
        self._trend_group_id = trend_group_id
        self._trend_def_id = trend_def_id
        self._time_exponent = time_exponent
        self._format = format
        self._unit_id = unit_id
        self._color = color
        self._axis_label = axis_label

    @classmethod
    def from_dict(cls, dikt) -> 'Trend':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Trend of this Trend.  # noqa: E501
        :rtype: Trend
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Trend.

        none  # noqa: E501

        :return: The id of this Trend.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Trend.

        none  # noqa: E501

        :param id: The id of this Trend.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this Trend.

        none  # noqa: E501

        :return: The name of this Trend.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Trend.

        none  # noqa: E501

        :param name: The name of this Trend.
        :type name: str
        """
        if name is not None and not re.search(r'^.{0,30}', name):  # noqa: E501
            raise ValueError("Invalid value for `name`, must be a follow pattern or equal to `/^.{0,30}/`")  # noqa: E501

        self._name = name

    @property
    def trend_group_id(self):
        """Gets the trend_group_id of this Trend.

        none  # noqa: E501

        :return: The trend_group_id of this Trend.
        :rtype: int
        """
        return self._trend_group_id

    @trend_group_id.setter
    def trend_group_id(self, trend_group_id):
        """Sets the trend_group_id of this Trend.

        none  # noqa: E501

        :param trend_group_id: The trend_group_id of this Trend.
        :type trend_group_id: int
        """

        self._trend_group_id = trend_group_id

    @property
    def trend_def_id(self):
        """Gets the trend_def_id of this Trend.

        none  # noqa: E501

        :return: The trend_def_id of this Trend.
        :rtype: str
        """
        return self._trend_def_id

    @trend_def_id.setter
    def trend_def_id(self, trend_def_id):
        """Sets the trend_def_id of this Trend.

        none  # noqa: E501

        :param trend_def_id: The trend_def_id of this Trend.
        :type trend_def_id: str
        """

        self._trend_def_id = trend_def_id

    @property
    def time_exponent(self):
        """Gets the time_exponent of this Trend.

        none  # noqa: E501

        :return: The time_exponent of this Trend.
        :rtype: int
        """
        return self._time_exponent

    @time_exponent.setter
    def time_exponent(self, time_exponent):
        """Sets the time_exponent of this Trend.

        none  # noqa: E501

        :param time_exponent: The time_exponent of this Trend.
        :type time_exponent: int
        """

        self._time_exponent = time_exponent

    @property
    def format(self):
        """Gets the format of this Trend.

        none  # noqa: E501

        :return: The format of this Trend.
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this Trend.

        none  # noqa: E501

        :param format: The format of this Trend.
        :type format: str
        """

        self._format = format

    @property
    def unit_id(self):
        """Gets the unit_id of this Trend.

        none  # noqa: E501

        :return: The unit_id of this Trend.
        :rtype: str
        """
        return self._unit_id

    @unit_id.setter
    def unit_id(self, unit_id):
        """Sets the unit_id of this Trend.

        none  # noqa: E501

        :param unit_id: The unit_id of this Trend.
        :type unit_id: str
        """

        self._unit_id = unit_id

    @property
    def color(self):
        """Gets the color of this Trend.


        :return: The color of this Trend.
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this Trend.


        :param color: The color of this Trend.
        :type color: str
        """

        self._color = color

    @property
    def axis_label(self):
        """Gets the axis_label of this Trend.


        :return: The axis_label of this Trend.
        :rtype: str
        """
        return self._axis_label

    @axis_label.setter
    def axis_label(self, axis_label):
        """Sets the axis_label of this Trend.


        :param axis_label: The axis_label of this Trend.
        :type axis_label: str
        """

        self._axis_label = axis_label
