from .event import router as events_router
from .event_def import router as event_defs_router
from .trend_def import router as trend_defs_router
from .trend import router as trend_router
from .auth import router as auth_router
from .link import router as link_router
from .node import router as node_router
from .template import router as template_router
from .unit import router as unit_router
from .trend_group import router as trend_groups_router
from .trend_writer import router as trend_writer_router
from .simulation import router as simulation_router
from .trend_param import router as trend_params_router
from .trend_data import router as trend_data_router
from .simulation_def import router as simulation_defs_router
from .simulation_data import router as simulation_data_router
from .simulation_param import router as simulation_params_router
from .leak_detector import router as leak_detector_router
