from .event import router as event_router
from .event_def import router as event_def_router
from .trend_def import router as trend_def_router
from .trend import router as trend_router
from .auth import router as auth_router
from .link import router as link_router
from .node import router as node_router
from .template import router as template_router
from .unit import router as unit_router
from .trend_group import router as trend_group_router
from .trend_writer import router as trend_writer_router
from .simulation import router as simulation_router
from .trend_param import router as trend_param_router
from .trend_data import router as trend_data_router
from .simulation_def import router as simulation_def_router
from .simulation_data import router as simulation_data_router
from .simulation_param import router as simulation_param_router
from .leak_detector import router as leak_detector_router
from .pipeline import router as pipeline_router
from .pipeline_param import router as pipeline_param_router
from .method import router as method_router
from .method_def import router as method_def_router
from .method_param import router as method_param_router
from .method_data import router as method_data_router
