--- 
#db_uri: mssql+pyodbc://@localhost/NefrytLDS_Zygmuntow_2022?driver=ODBC+Driver+17+for+SQL+Server
# db_uri: mssql+pyodbc://sa:Onyks$us@serverdb:1447/NefrytLDSDemo?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=Yes&Encrypt=No
# db_uri: mssql+pyodbc://sa:Onyks$us@localhost:1447/OnyksLDSDemo?driver=ODBC+Driver+17+for+SQL+Server
# db_uri: mssql+pyodbc://sa:Onyks$us@serverdb:1447/NefrytLDSDemo?driver=ODBC+Driver+17+for+SQL+Server


db_uri: mssql+pyodbc://sa:Onyks$us@owl.agatit.pl:1449/NefrytLDS_Zygmuntow_2024?driver=ODBC+Driver+17+for+SQL+Server
test_db_uri: mssql+pyodbc://sa:praktyka@localhost/NefrytLDS_Test_Database?driver=ODBC+Driver+17+for+SQL+Server
verbosity: INFO # DEBUG, WARNING, ERROR, ...