--- 
#db_uri: mssql+pyodbc://sa:Onyks$us@serverdb:1447/NefrytLDSDemo?driver=ODBC+Driver+17+for+SQL+Server
# db_uri: mssql+pyodbc://sa:Onyks$us@serverdb:1447/NefrytLDSDemo?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=Yes&Encrypt=No
#db_uri: mssql+pyodbc://sa:Onyks$us@localhost:1447/OnyksLDSDemo?driver=ODBC+Driver+17+for+SQL+Server
db_uri: mssql+pyodbc://sa:Onyks$us@serverdb:1447/NefrytLDSDemo?driver=ODBC+Driver+17+for+SQL+Server
verbosity: INFO # DEBUG, WARNING, ERROR, ...