db_uri: mssql+pyodbc://sa:Onyks$us@owl.agatit.pl:1449/NefrytLDS_Zygmuntow_2025?driver=ODBC+Driver+17+for+SQL+Server
verbosity: INFO
trends_writer:
  modbus_port: 502
  log_profiler: False
  profiler_filename: profiler.log
  use_past_trend_data: False
  logging:
    version: 1

    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        stream: ext://sys.stdout

      manager:
        class: logging.FileHandler
        filename: default_log.log
        level: INFO

    loggers:
      trends_writer:
        level: INFO
        handlers: [console]

      trends_writer.trend:
        level: INFO
        handlers: [console]
        propagate: False

      trends_writer.modbus:
        level: INFO
        handlers: [console]
        propagate: False

      trends_writer.plant:
        level: INFO
        handlers: [console]
        propagate: False

      trends_writer.profiler:
        level: WARNING
        handlers: [console]
        propagate: False

      trends_writer.past_writer:
        level: INFO
        handlers: [ console ]
        propagate: False

simulator:
  logging:
    version: 1

    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        stream: ext://sys.stdout

      manager:
        class: logging.FileHandler
        filename: default_log.log
        level: INFO

    loggers:
      simulator:
        level: INFO
        handlers: [ console ]

      simulator.simulations:
        level: INFO
        handlers: [ console ]
        propagate: False

      simulator.simulation_manager:
        level: INFO
        handlers: [ console ]
        propagate: False

  displayer_ports:
    4: 11111
    5: 22222
leak_detector:
  plot_heatmap: False
  logging:
    version: 1
    disable_existing_loggers: True

    handlers:
      console:
        class: logging.StreamHandler
        level: DEBUG
        stream: ext://sys.stdout

      manager:
        class: logging.FileHandler
        filename: default_log.log
        level: INFO

    loggers:
      leak_detector:
        level: INFO
        handlers: [ console ]
        propagate: False

      leak_detector.detector_display:
        level: DEBUG
        handlers: [ console ]
        propagate: False

      leak_detector.event:
        level: INFO
        handlers: [ console ]
        propagate: False

      leak_detector.plant:
        level: INFO
        handlers: [ console ]
        propagate: False

      leak_detector.segment:
        level: INFO
        handlers: [ console ]
        propagate: False

      leak_detector.trend:
        level: INFO
        handlers: [ console ]
        propagate: False

      leak_detector.past_detector:
        level: INFO
        handlers: [ console ]
        propagate: False

      leak_detector.method:
        level: DEBUG
        handlers: [ console ]
        propagate: False

