/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditorNode
 */
export interface EditorNode {
    /**
     * none
     * @type {number}
     * @memberof EditorNode
     */
    posX: number;
    /**
     * none
     * @type {number}
     * @memberof EditorNode
     */
    posY: number;
}

export function EditorNodeFromJSON(json: any): EditorNode {
    return EditorNodeFromJSONTyped(json, false);
}

export function EditorNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditorNode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'posX': json['PosX'],
        'posY': json['PosY'],
    };
}

export function EditorNodeToJSON(value?: EditorNode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'PosX': value.posX,
        'PosY': value.posY,
    };
}

