/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditorPipeline
 */
export interface EditorPipeline {
    /**
     * none
     * @type {number}
     * @memberof EditorPipeline
     */
    areaWidth: number;
    /**
     * none
     * @type {number}
     * @memberof EditorPipeline
     */
    areaHeight: number;
    /**
     * none
     * @type {number}
     * @memberof EditorPipeline
     */
    areaWidthDivision: number;
    /**
     * none
     * @type {number}
     * @memberof EditorPipeline
     */
    areaHeightDivision: number;
}

export function EditorPipelineFromJSON(json: any): EditorPipeline {
    return EditorPipelineFromJSONTyped(json, false);
}

export function EditorPipelineFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditorPipeline {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'areaWidth': json['AreaWidth'],
        'areaHeight': json['AreaHeight'],
        'areaWidthDivision': json['AreaWidthDivision'],
        'areaHeightDivision': json['AreaHeightDivision'],
    };
}

export function EditorPipelineToJSON(value?: EditorPipeline | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'AreaWidth': value.areaWidth,
        'AreaHeight': value.areaHeight,
        'AreaWidthDivision': value.areaWidthDivision,
        'AreaHeightDivision': value.areaHeightDivision,
    };
}

