/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
    /**
     * none
     * @type {number}
     * @memberof InlineResponse200
     */
    readonly iD: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    methodDefID: number;
    /**
     * 
     * @type {number}
     * @memberof InlineResponse200
     */
    pipelineID: number;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse200
     */
    name?: string;
}

export function InlineResponse200FromJSON(json: any): InlineResponse200 {
    return InlineResponse200FromJSONTyped(json, false);
}

export function InlineResponse200FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse200 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'methodDefID': json['MethodDefID'],
        'pipelineID': json['PipelineID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function InlineResponse200ToJSON(value?: InlineResponse200 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'MethodDefID': value.methodDefID,
        'PipelineID': value.pipelineID,
        'Name': value.name,
    };
}

