/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MethodDef
 */
export interface MethodDef {
    /**
     * none
     * @type {number}
     * @memberof MethodDef
     */
    readonly iD: number;
    /**
     * none
     * @type {string}
     * @memberof MethodDef
     */
    name?: string;
}

export function MethodDefFromJSON(json: any): MethodDef {
    return MethodDefFromJSONTyped(json, false);
}

export function MethodDefFromJSONTyped(json: any, ignoreDiscriminator: boolean): MethodDef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function MethodDefToJSON(value?: MethodDef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
    };
}

