/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EditorNode,
    EditorNodeFromJSON,
    EditorNodeFromJSONTyped,
    EditorNodeToJSON,
} from './EditorNode';

/**
 * 
 * @export
 * @interface Node
 */
export interface Node {
    /**
     * none
     * @type {number}
     * @memberof Node
     */
    readonly iD: number;
    /**
     * none
     * @type {string}
     * @memberof Node
     */
    type: string;
    /**
     * none
     * @type {number}
     * @memberof Node
     */
    trendID?: number | null;
    /**
     * none
     * @type {string}
     * @memberof Node
     */
    name?: string;
    /**
     * 
     * @type {EditorNode}
     * @memberof Node
     */
    editorParams?: EditorNode;
}

export function NodeFromJSON(json: any): Node {
    return NodeFromJSONTyped(json, false);
}

export function NodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Node {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'type': json['Type'],
        'trendID': !exists(json, 'TrendID') ? undefined : json['TrendID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'editorParams': !exists(json, 'EditorParams') ? undefined : EditorNodeFromJSON(json['EditorParams']),
    };
}

export function NodeToJSON(value?: Node | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Type': value.type,
        'TrendID': value.trendID,
        'Name': value.name,
        'EditorParams': EditorNodeToJSON(value.editorParams),
    };
}

