/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipelineNode
 */
export interface PipelineNode {
    /**
     * none
     * @type {number}
     * @memberof PipelineNode
     */
    readonly iD: number;
    /**
     * none
     * @type {number}
     * @memberof PipelineNode
     */
    nodeID: number;
    /**
     * none
     * @type {boolean}
     * @memberof PipelineNode
     */
    first?: boolean;
}

export function PipelineNodeFromJSON(json: any): PipelineNode {
    return PipelineNodeFromJSONTyped(json, false);
}

export function PipelineNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineNode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'nodeID': json['NodeID'],
        'first': !exists(json, 'First') ? undefined : json['First'],
    };
}

export function PipelineNodeToJSON(value?: PipelineNode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NodeID': value.nodeID,
        'First': value.first,
    };
}

