/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendParamDef
 */
export interface TrendParamDef {
    /**
     * none
     * @type {number}
     * @memberof TrendParamDef
     */
    readonly iD: number;
    /**
     * none
     * @type {number}
     * @memberof TrendParamDef
     */
    trendDefID: number;
    /**
     * none
     * @type {string}
     * @memberof TrendParamDef
     */
    name?: string;
    /**
     * none
     * @type {string}
     * @memberof TrendParamDef
     */
    dataType?: string;
}

export function TrendParamDefFromJSON(json: any): TrendParamDef {
    return TrendParamDefFromJSONTyped(json, false);
}

export function TrendParamDefFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrendParamDef {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'trendDefID': json['TrendDefID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'dataType': !exists(json, 'DataType') ? undefined : json['DataType'],
    };
}

export function TrendParamDefToJSON(value?: TrendParamDef | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'TrendDefID': value.trendDefID,
        'Name': value.name,
        'DataType': value.dataType,
    };
}

