/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendParam
 */
export interface TrendParam {
    /**
     * none
     * @type {number}
     * @memberof TrendParam
     */
    readonly trendID: number;
    /**
     * 
     * @type {string}
     * @memberof TrendParam
     */
    readonly trendParamDefID: string;
    /**
     * 
     * @type {string}
     * @memberof TrendParam
     */
    readonly name?: string;
    /**
     * 
     * @type {string}
     * @memberof TrendParam
     */
    readonly dataType?: string;
    /**
     * 
     * @type {string}
     * @memberof TrendParam
     */
    value: string;
}

export function TrendParamFromJSON(json: any): TrendParam {
    return TrendParamFromJSONTyped(json, false);
}

export function TrendParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrendParam {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'trendID': json['TrendID'],
        'trendParamDefID': json['TrendParamDefID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'dataType': !exists(json, 'DataType') ? undefined : json['DataType'],
        'value': json['Value'],
    };
}

export function TrendParamToJSON(value?: TrendParam | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Value': value.value,
    };
}

