/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Trend
 */
export interface Trend {
    /**
     * none
     * @type {number}
     * @memberof Trend
     */
    readonly iD: number;
    /**
     * none
     * @type {string}
     * @memberof Trend
     */
    name?: string;
    /**
     * none
     * @type {number}
     * @memberof Trend
     */
    trendGroupID?: number;
    /**
     * none
     * @type {string}
     * @memberof Trend
     */
    trendDefID?: string;
    /**
     * none
     * @type {number}
     * @memberof Trend
     */
    timeExponent?: number;
    /**
     * none
     * @type {string}
     * @memberof Trend
     */
    format?: string;
    /**
     * none
     * @type {string}
     * @memberof Trend
     */
    unitID?: string;
    /**
     * 
     * @type {string}
     * @memberof Trend
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof Trend
     */
    axisLabel?: string;
}

export function TrendFromJSON(json: any): Trend {
    return TrendFromJSONTyped(json, false);
}

export function TrendFromJSONTyped(json: any, ignoreDiscriminator: boolean): Trend {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'trendGroupID': !exists(json, 'TrendGroupID') ? undefined : json['TrendGroupID'],
        'trendDefID': !exists(json, 'TrendDefID') ? undefined : json['TrendDefID'],
        'timeExponent': !exists(json, 'TimeExponent') ? undefined : json['TimeExponent'],
        'format': !exists(json, 'Format') ? undefined : json['Format'],
        'unitID': !exists(json, 'UnitID') ? undefined : json['UnitID'],
        'color': !exists(json, 'Color') ? undefined : json['Color'],
        'axisLabel': !exists(json, 'AxisLabel') ? undefined : json['AxisLabel'],
    };
}

export function TrendToJSON(value?: Trend | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'TrendGroupID': value.trendGroupID,
        'TrendDefID': value.trendDefID,
        'TimeExponent': value.timeExponent,
        'Format': value.format,
        'UnitID': value.unitID,
        'Color': value.color,
        'AxisLabel': value.axisLabel,
    };
}

