/* tslint:disable */
/* eslint-disable */
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendGroup
 */
export interface TrendGroup {
    /**
     * none
     * @type {number}
     * @memberof TrendGroup
     */
    readonly iD: number;
    /**
     * none
     * @type {string}
     * @memberof TrendGroup
     */
    name: string;
    /**
     * none
     * @type {boolean}
     * @memberof TrendGroup
     */
    analisisOnly: boolean;
}

export function TrendGroupFromJSON(json: any): TrendGroup {
    return TrendGroupFromJSONTyped(json, false);
}

export function TrendGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrendGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'iD': json['ID'],
        'name': json['Name'],
        'analisisOnly': json['AnalisisOnly'],
    };
}

export function TrendGroupToJSON(value?: TrendGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
        'AnalisisOnly': value.analisisOnly,
    };
}

