openapi: 3.0.0
info:
  title: Nefryt LDS API
  description: Database API for Nefryt LDS
  version: 1.0.0
servers:
  - url: http://192.168.1.231:8080/
    description: Test server
  - url: http://localhost:8080/
    description: Developer's local server
paths:
  # ref to files ./paths/endpoint.yaml
  /trend:
    $ref: "./paths/trends.yaml"
  /trend/{trendId}:
    $ref: "./paths/trend.yaml"
  /trend/{trendId}/param:
    $ref: "./paths/trendParams.yaml"
  /trend/{trendId}/param/{trendParamDefId}:
    $ref: "./paths/trendParam.yaml"
  /trend/{trendIdList}/data/{begin}/{end}/{samples}:
    $ref: "./paths/trendData.yaml"
  /trend/{trendIdList}/current_data/{period}/{samples}:
    $ref: "./paths/trendCurrentData.yaml"    
  /trend_def:
    $ref: "./paths/trendDefs.yaml"    
    
  /node:
    $ref: "./paths/nodes.yaml"
  /node/{nodeId}:
    $ref: "./paths/node.yaml"

  /link:
    $ref: "./paths/links.yaml"
  /link/{linkId}:
    $ref: "./paths/link.yaml"    

  /pipeline:
    $ref: "./paths/pipelines.yaml"
  /pipeline/{pipelineId}:
    $ref: "./paths/pipeline.yaml"
  /pipeline/{pipelineId}/param:
    $ref: "./paths/pipelineParams.yaml"
  /pipeline/{pipelineId}/param/{pipelineParamDefId}:
    $ref: "./paths/pipelineParam.yaml"   
  /pipeline/{pipelineId}/method:
    $ref: "./paths/methods.yaml" 
  /pipeline/{pipelineId}/method/{methodId}:
    $ref: "./paths/method.yaml"     
  /pipeline/{pipelineId}/method/{methodId}/param:
    $ref: "./paths/methodParams.yaml"
  /pipeline/{pipelineId}/method/{methodId}/param/{methodParamDefId}:
    $ref: "./paths/methodParam.yaml"       

  /event:
    $ref: "./paths/events.yaml"
  /event/{eventId}:
    $ref: "./paths/event.yaml"
  /event/{eventId}/ack:
    $ref: "./paths/eventAck.yaml"

  /unit:
    $ref: "./paths/units.yaml"
  /unit/{unitId}:
    $ref: "./paths/unit.yaml"    

  /auth/login:
    $ref: "./paths/authLogin.yaml"
  /auth/refresh:
    $ref: "./paths/authRefresh.yaml"

components:
  parameters:
    $ref: "./parameters/_index.yaml"
  schemas:
    $ref: "./schemas/_index.yaml"
  responses:
    $ref: "./responses/_index.yaml"
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes    
      x-bearerInfoFunc: api.controllers.security_controller.decode_token

security:
  - bearerAuth: []       
