// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Pipeline,
    PipelineFromJSON,
    PipelineToJSON,
} from './';

/**
 * 
 * @export
 * @interface EditorPipelineApi
 */
export interface EditorPipelineApi  {
    /**
     * none
     * @type {number}
     * @memberof EditorPipelineApi
     */
    iD: number;
    /**
     * none
     * @type {number}
     * @memberof EditorPipelineApi
     */
    areaWidth: number;
    /**
     * none
     * @type {number}
     * @memberof EditorPipelineApi
     */
    areaHeight: number;
    /**
     * none
     * @type {number}
     * @memberof EditorPipelineApi
     */
    areaWidthDivision: number;
    /**
     * none
     * @type {number}
     * @memberof EditorPipelineApi
     */
    areaHeightDivision: number;
    /**
     * none
     * @type {number}
     * @memberof EditorPipelineApi
     */
    sIUnitID: number;
    /**
     * 
     * @type {Pipeline}
     * @memberof EditorPipelineApi
     */
    pipeline?: Pipeline;
}

export function EditorPipelineApiFromJSON(json: any): EditorPipelineApi {
    return {
        'iD': json['ID'],
        'areaWidth': json['AreaWidth'],
        'areaHeight': json['AreaHeight'],
        'areaWidthDivision': json['AreaWidthDivision'],
        'areaHeightDivision': json['AreaHeightDivision'],
        'sIUnitID': json['SIUnitID'],
        'pipeline': !exists(json, 'Pipeline') ? undefined : json['Pipeline'],
    };
}

export function EditorPipelineApiToJSON(value?: EditorPipelineApi): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'ID': value.iD,
        'AreaWidth': value.areaWidth,
        'AreaHeight': value.areaHeight,
        'AreaWidthDivision': value.areaWidthDivision,
        'AreaHeightDivision': value.areaHeightDivision,
        'SIUnitID': value.sIUnitID,
        'Pipeline': value.pipeline,
    };
}


