// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Node,
    NodeFromJSON,
    NodeToJSON,
} from './';

/**
 * 
 * @export
 * @interface EditorNodeApi
 */
export interface EditorNodeApi  {
    /**
     * none
     * @type {number}
     * @memberof EditorNodeApi
     */
    pipelineID: number;
    /**
     * none
     * @type {number}
     * @memberof EditorNodeApi
     */
    methodID: number;
    /**
     * none
     * @type {number}
     * @memberof EditorNodeApi
     */
    methodParamDefID?: number;
    /**
     * none
     * @type {string}
     * @memberof EditorNodeApi
     */
    dataType?: string;
    /**
     * none
     * @type {string}
     * @memberof EditorNodeApi
     */
    name?: string;
    /**
     * none
     * @type {string}
     * @memberof EditorNodeApi
     */
    value?: string;
    /**
     * 
     * @type {Node}
     * @memberof EditorNodeApi
     */
    node?: Node;
}

export function EditorNodeApiFromJSON(json: any): EditorNodeApi {
    return {
        'pipelineID': json['PipelineID'],
        'methodID': json['MethodID'],
        'methodParamDefID': !exists(json, 'MethodParamDefID') ? undefined : json['MethodParamDefID'],
        'dataType': !exists(json, 'DataType') ? undefined : json['DataType'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'value': !exists(json, 'Value') ? undefined : json['Value'],
        'node': !exists(json, 'Node') ? undefined : json['Node'],
    };
}

export function EditorNodeApiToJSON(value?: EditorNodeApi): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'PipelineID': value.pipelineID,
        'MethodID': value.methodID,
        'MethodParamDefID': value.methodParamDefID,
        'DataType': value.dataType,
        'Name': value.name,
        'Value': value.value,
        'Node': value.node,
    };
}


