// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Information
 */
export interface Information  {
    /**
     * 
     * @type {number}
     * @memberof Information
     */
    status: number;
    /**
     * 
     * @type {number}
     * @memberof Information
     */
    affected: number;
    /**
     * 
     * @type {string}
     * @memberof Information
     */
    message: string;
}

export function InformationFromJSON(json: any): Information {
    return {
        'status': json['status'],
        'affected': json['affected'],
        'message': json['message'],
    };
}

export function InformationToJSON(value?: Information): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'status': value.status,
        'affected': value.affected,
        'message': value.message,
    };
}


