// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginPermissions
 */
export interface LoginPermissions  {
    /**
     * 
     * @type {string}
     * @memberof LoginPermissions
     */
    username?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LoginPermissions
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginPermissions
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof LoginPermissions
     */
    refreshToken: string;
    /**
     * 
     * @type {string}
     * @memberof LoginPermissions
     */
    refreshTokenExpiration: string;
    /**
     * 
     * @type {Array<{ [key: string]: object; }>}
     * @memberof LoginPermissions
     */
    permissions?: Array<{ [key: string]: object; }>;
}

export function LoginPermissionsFromJSON(json: any): LoginPermissions {
    return {
        'username': !exists(json, 'username') ? undefined : json['username'],
        'success': !exists(json, 'success') ? undefined : json['success'],
        'token': json['token'],
        'refreshToken': json['refreshToken'],
        'refreshTokenExpiration': json['refreshTokenExpiration'],
        'permissions': !exists(json, 'permissions') ? undefined : json['permissions'],
    };
}

export function LoginPermissionsToJSON(value?: LoginPermissions): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'username': value.username,
        'success': value.success,
        'token': value.token,
        'refreshToken': value.refreshToken,
        'refreshTokenExpiration': value.refreshTokenExpiration,
        'permissions': value.permissions,
    };
}


