// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Login
 */
export interface Login  {
    /**
     * 
     * @type {string}
     * @memberof Login
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof Login
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof Login
     */
    deviceId?: string;
    /**
     * 
     * @type {string}
     * @memberof Login
     */
    deviceName?: string;
}

export function LoginFromJSON(json: any): Login {
    return {
        'username': json['username'],
        'password': json['password'],
        'deviceId': !exists(json, 'deviceId') ? undefined : json['deviceId'],
        'deviceName': !exists(json, 'deviceName') ? undefined : json['deviceName'],
    };
}

export function LoginToJSON(value?: Login): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'username': value.username,
        'password': value.password,
        'deviceId': value.deviceId,
        'deviceName': value.deviceName,
    };
}


