// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MethodParamDef
 */
export interface MethodParamDef  {
    /**
     * none
     * @type {number}
     * @memberof MethodParamDef
     */
    readonly iD: number;
    /**
     * none
     * @type {number}
     * @memberof MethodParamDef
     */
    methodDefID?: number;
    /**
     * none
     * @type {string}
     * @memberof MethodParamDef
     */
    name?: string;
    /**
     * none
     * @type {string}
     * @memberof MethodParamDef
     */
    dataType?: string;
}

export function MethodParamDefFromJSON(json: any): MethodParamDef {
    return {
        'iD': json['ID'],
        'methodDefID': !exists(json, 'MethodDefID') ? undefined : json['MethodDefID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'dataType': !exists(json, 'DataType') ? undefined : json['DataType'],
    };
}

export function MethodParamDefToJSON(value?: MethodParamDef): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'MethodDefID': value.methodDefID,
        'Name': value.name,
        'DataType': value.dataType,
    };
}


