// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MethodParam
 */
export interface MethodParam  {
    /**
     * none
     * @type {number}
     * @memberof MethodParam
     */
    pipelineID: number;
    /**
     * none
     * @type {number}
     * @memberof MethodParam
     */
    methodID: number;
    /**
     * none
     * @type {number}
     * @memberof MethodParam
     */
    methodParamDefID?: number;
    /**
     * none
     * @type {string}
     * @memberof MethodParam
     */
    dataType?: string;
    /**
     * none
     * @type {string}
     * @memberof MethodParam
     */
    name?: string;
    /**
     * none
     * @type {string}
     * @memberof MethodParam
     */
    value?: string;
}

export function MethodParamFromJSON(json: any): MethodParam {
    return {
        'pipelineID': json['PipelineID'],
        'methodID': json['MethodID'],
        'methodParamDefID': !exists(json, 'MethodParamDefID') ? undefined : json['MethodParamDefID'],
        'dataType': !exists(json, 'DataType') ? undefined : json['DataType'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'value': !exists(json, 'Value') ? undefined : json['Value'],
    };
}

export function MethodParamToJSON(value?: MethodParam): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'PipelineID': value.pipelineID,
        'MethodID': value.methodID,
        'MethodParamDefID': value.methodParamDefID,
        'DataType': value.dataType,
        'Name': value.name,
        'Value': value.value,
    };
}


