// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Method
 */
export interface Method  {
    /**
     * none
     * @type {number}
     * @memberof Method
     */
    readonly iD: number;
    /**
     * 
     * @type {number}
     * @memberof Method
     */
    methodDefID: number;
    /**
     * 
     * @type {number}
     * @memberof Method
     */
    pipelineID: number;
    /**
     * 
     * @type {string}
     * @memberof Method
     */
    name?: string;
}

export function MethodFromJSON(json: any): Method {
    return {
        'iD': json['ID'],
        'methodDefID': json['MethodDefID'],
        'pipelineID': json['PipelineID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
    };
}

export function MethodToJSON(value?: Method): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'MethodDefID': value.methodDefID,
        'PipelineID': value.pipelineID,
        'Name': value.name,
    };
}


