// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipelineParamDef
 */
export interface PipelineParamDef  {
    /**
     * none
     * @type {number}
     * @memberof PipelineParamDef
     */
    readonly iD: number;
    /**
     * none
     * @type {number}
     * @memberof PipelineParamDef
     */
    pipelineDefID?: number;
    /**
     * none
     * @type {string}
     * @memberof PipelineParamDef
     */
    name?: string;
    /**
     * none
     * @type {string}
     * @memberof PipelineParamDef
     */
    dataType?: string;
}

export function PipelineParamDefFromJSON(json: any): PipelineParamDef {
    return {
        'iD': json['ID'],
        'pipelineDefID': !exists(json, 'PipelineDefID') ? undefined : json['PipelineDefID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'dataType': !exists(json, 'DataType') ? undefined : json['DataType'],
    };
}

export function PipelineParamDefToJSON(value?: PipelineParamDef): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'PipelineDefID': value.pipelineDefID,
        'Name': value.name,
        'DataType': value.dataType,
    };
}


