// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipelineParam
 */
export interface PipelineParam  {
    /**
     * none
     * @type {number}
     * @memberof PipelineParam
     */
    pipelineID: number;
    /**
     * none
     * @type {number}
     * @memberof PipelineParam
     */
    pipelineParamDefID?: number;
    /**
     * none
     * @type {string}
     * @memberof PipelineParam
     */
    dataType?: string;
    /**
     * none
     * @type {string}
     * @memberof PipelineParam
     */
    name?: string;
    /**
     * none
     * @type {string}
     * @memberof PipelineParam
     */
    value?: string;
}

export function PipelineParamFromJSON(json: any): PipelineParam {
    return {
        'pipelineID': json['PipelineID'],
        'pipelineParamDefID': !exists(json, 'PipelineParamDefID') ? undefined : json['PipelineParamDefID'],
        'dataType': !exists(json, 'DataType') ? undefined : json['DataType'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'value': !exists(json, 'Value') ? undefined : json['Value'],
    };
}

export function PipelineParamToJSON(value?: PipelineParam): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'PipelineID': value.pipelineID,
        'PipelineParamDefID': value.pipelineParamDefID,
        'DataType': value.dataType,
        'Name': value.name,
        'Value': value.value,
    };
}


