// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendDataTrends
 */
export interface TrendDataTrends  {
    /**
     * 
     * @type {number}
     * @memberof TrendDataTrends
     */
    trendID?: number;
    /**
     * 
     * @type {string}
     * @memberof TrendDataTrends
     */
    color?: string;
    /**
     * 
     * @type {string}
     * @memberof TrendDataTrends
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TrendDataTrends
     */
    axisLabel?: string;
}

export function TrendDataTrendsFromJSON(json: any): TrendDataTrends {
    return {
        'trendID': !exists(json, 'TrendID') ? undefined : json['TrendID'],
        'color': !exists(json, 'Color') ? undefined : json['Color'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'axisLabel': !exists(json, 'AxisLabel') ? undefined : json['AxisLabel'],
    };
}

export function TrendDataTrendsToJSON(value?: TrendDataTrends): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'TrendID': value.trendID,
        'Color': value.color,
        'Name': value.name,
        'AxisLabel': value.axisLabel,
    };
}


