// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendParamApi
 */
export interface TrendParamApi  {
    /**
     * none
     * @type {number}
     * @memberof TrendParamApi
     */
    trendID: number;
    /**
     * none
     * @type {number}
     * @memberof TrendParamApi
     */
    trendDefID?: number;
    /**
     * 
     * @type {string}
     * @memberof TrendParamApi
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof TrendParamApi
     */
    dataType?: string;
    /**
     * 
     * @type {number}
     * @memberof TrendParamApi
     */
    trendParamDefID?: number;
    /**
     * 
     * @type {string}
     * @memberof TrendParamApi
     */
    value?: string;
}

export function TrendParamApiFromJSON(json: any): TrendParamApi {
    return {
        'trendID': json['TrendID'],
        'trendDefID': !exists(json, 'TrendDefID') ? undefined : json['TrendDefID'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'dataType': !exists(json, 'DataType') ? undefined : json['DataType'],
        'trendParamDefID': !exists(json, 'TrendParamDefID') ? undefined : json['TrendParamDefID'],
        'value': !exists(json, 'Value') ? undefined : json['Value'],
    };
}

export function TrendParamApiToJSON(value?: TrendParamApi): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'TrendID': value.trendID,
        'TrendDefID': value.trendDefID,
        'Name': value.name,
        'DataType': value.dataType,
        'TrendParamDefID': value.trendParamDefID,
        'Value': value.value,
    };
}


