// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendData
 */
export interface TrendData  {
    [key: string]: number | any;
    /**
     * 
     * @type {number}
     * @memberof TrendData
     */
    timestamp: number;
    /**
     * 
     * @type {number}
     * @memberof TrendData
     */
    timestampMs: number;
}

export function TrendDataFromJSON(json: any): TrendData {
    return {
            ...json,
        'timestamp': json['Timestamp'],
        'timestampMs': json['TimestampMs'],
    };
}

export function TrendDataToJSON(value?: TrendData): any {
    if (value === undefined) {
        return undefined;
    }
    return {
            ...value,
        'Timestamp': value.timestamp,
        'TimestampMs': value.timestampMs,
    };
}


