// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendDef
 */
export interface TrendDef  {
    /**
     * none
     * @type {number}
     * @memberof TrendDef
     */
    readonly iD: number;
    /**
     * none
     * @type {string}
     * @memberof TrendDef
     */
    name: string;
    /**
     * none
     * @type {number}
     * @memberof TrendDef
     */
    timeExponent: number;
    /**
     * none
     * @type {string}
     * @memberof TrendDef
     */
    format: string;
    /**
     * none
     * @type {string}
     * @memberof TrendDef
     */
    sIUnitTID: string;
}

export function TrendDefFromJSON(json: any): TrendDef {
    return {
        'iD': json['ID'],
        'name': json['Name'],
        'timeExponent': json['TimeExponent'],
        'format': json['Format'],
        'sIUnitTID': json['SIUnitTID'],
    };
}

export function TrendDefToJSON(value?: TrendDef): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'Name': value.name,
        'TimeExponent': value.timeExponent,
        'Format': value.format,
        'SIUnitTID': value.sIUnitTID,
    };
}


