// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrendDataApi
 */
export interface TrendDataApi  {
    /**
     * none
     * @type {number}
     * @memberof TrendDataApi
     */
    trendDefID: number;
    /**
     * none
     * @type {number}
     * @memberof TrendDataApi
     */
    time: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof TrendDataApi
     */
    data: Array<number>;
}

export function TrendDataApiFromJSON(json: any): TrendDataApi {
    return {
        'trendDefID': json['TrendDefID'],
        'time': json['Time'],
        'data': json['Data'],
    };
}

export function TrendDataApiToJSON(value?: TrendDataApi): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'TrendDefID': value.trendDefID,
        'Time': value.time,
        'Data': value.data,
    };
}


