// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Unauthorized
 */
export interface Unauthorized  {
    /**
     * 
     * @type {string}
     * @memberof Unauthorized
     */
    error: string;
    /**
     * 
     * @type {number}
     * @memberof Unauthorized
     */
    status: number;
    /**
     * 
     * @type {string}
     * @memberof Unauthorized
     */
    timestamp: string;
    /**
     * 
     * @type {string}
     * @memberof Unauthorized
     */
    path: string;
    /**
     * 
     * @type {string}
     * @memberof Unauthorized
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof Unauthorized
     */
    traceId?: string;
}

export function UnauthorizedFromJSON(json: any): Unauthorized {
    return {
        'error': json['error'],
        'status': json['status'],
        'timestamp': json['timestamp'],
        'path': json['path'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'traceId': !exists(json, 'traceId') ? undefined : json['traceId'],
    };
}

export function UnauthorizedToJSON(value?: Unauthorized): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'error': value.error,
        'status': value.status,
        'timestamp': value.timestamp,
        'path': value.path,
        'message': value.message,
        'traceId': value.traceId,
    };
}


