"""Trend table add TimeDelta

Revision ID: 0da9a491388c
Revises: 5a77d4e34577
Create Date: 2025-08-12 08:14:19.283577

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

revision: str = '0da9a491388c'
down_revision: Union[str, None] = '5a77d4e34577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''IF EXISTS (
           SELECT 
            1
        FROM
            INFORMATION_SCHEMA.COLUMNS
        WHERE
          TABLE_SCHEMA = 'lds' 
          AND TABLE_NAME = 'EventDef'
          AND COLUMN_NAME = 'Silent'
          AND COLUMN_DEFAULT IS NULL
        )
        ALTER TABLE lds.EventDef
        ADD CONSTRAINT DF_EventDef_Silent
        DEFAULT '0' FOR Silent;
        ''')
    op.execute('''IF EXISTS (
               SELECT 
                1
            FROM
                INFORMATION_SCHEMA.COLUMNS
            WHERE
              TABLE_SCHEMA = 'lds' 
              AND TABLE_NAME = 'EventDef'
              AND COLUMN_NAME = 'Visible'
              AND COLUMN_DEFAULT IS NULL
            )
            ALTER TABLE lds.EventDef
            ADD CONSTRAINT DF_EventDef_Visible
            DEFAULT '1' FOR Visible;
            ''')
    op.execute('''IF EXISTS (
               SELECT 
                1
            FROM
                INFORMATION_SCHEMA.COLUMNS
            WHERE
              TABLE_SCHEMA = 'lds' 
              AND TABLE_NAME = 'EventDef'
              AND COLUMN_NAME = 'Enabled'
              AND COLUMN_DEFAULT IS NULL
            )
            ALTER TABLE lds.EventDef
            ADD CONSTRAINT DF_EventDef_Enabled
            DEFAULT '1' FOR Enabled;
            ''')
    op.alter_column('Link', 'Length',
               existing_type=sa.FLOAT(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True,
               schema='lds')
    op.execute('''IF EXISTS (
               SELECT 
                1
            FROM
                INFORMATION_SCHEMA.COLUMNS
            WHERE
              TABLE_SCHEMA = 'lds' 
              AND TABLE_NAME = 'PipelineNode'
              AND COLUMN_NAME = 'First'
              AND COLUMN_DEFAULT IS NULL
            )
            ALTER TABLE lds.PipelineNode
            ADD CONSTRAINT DF_PipelineNode_First
            DEFAULT '0' FOR First;
            ''')
    op.add_column('Trend', sa.Column('TimeDelta', sa.Integer(), nullable=True, server_default=sa.text('0')),
                  schema='lds')
    op.execute("UPDATE lds.[Trend] SET TimeDelta = 0 WHERE TimeDelta IS NULL")
    op.alter_column(
        'Trend',
        'TimeDelta',
        existing_type=sa.Integer(),
        nullable=False,
        schema='lds'
    )
    op.alter_column(
        'Trend',
        'TimeDelta',
        existing_type=sa.Integer(),
        server_default=None, # noqa
        schema='lds'
    )
    op.alter_column('TrendParamDef', 'DataType',
               existing_type=sa.CHAR(length=6, collation='SQL_Polish_CP1250_CS_AS'),
               type_=sa.VARCHAR(length=6, collation='SQL_Polish_CP1250_CS_AS'),
               existing_nullable=True,
               schema='lds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TrendParamDef', 'DataType',
               existing_type=sa.VARCHAR(length=6, collation='SQL_Polish_CP1250_CS_AS'),
               type_=sa.CHAR(length=6, collation='SQL_Polish_CP1250_CS_AS'),
               existing_nullable=True,
               schema='lds')
    op.drop_column('Trend', 'TimeDelta', schema='lds')
    op.alter_column('PipelineNode', 'First',
               existing_type=mssql.BIT(),
               existing_nullable=False,
               schema='lds')
    op.alter_column('Link', 'Length',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(precision=53),
               existing_nullable=True,
               schema='lds')
    op.alter_column('EventDef', 'Enabled',
               existing_type=mssql.BIT(),
               existing_nullable=False,
               schema='lds')
    op.alter_column('EventDef', 'Visible',
               existing_type=mssql.BIT(),
               existing_nullable=False,
               schema='lds')
    op.alter_column('EventDef', 'Silent',
               existing_type=mssql.BIT(),
               existing_nullable=False,
               schema='lds')
    # ### end Alembic commands ###
