"""Event and Method objects changes

Revision ID: 1d582453cff5
Revises: 54f295c48dbd
Create Date: 2026-01-20 19:48:43.477176

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

revision: str = '1d582453cff5'
down_revision: Union[str, None] = '54f295c48dbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PipelineNode', schema='lds')
    op.execute("""
    IF EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE name = 'EventMethod_fk'
    )
    BEGIN
        ALTER TABLE lds.[Event]
        DROP CONSTRAINT [EventMethod_fk]
    END
    """)
    op.execute("""
    IF EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE name = 'EventEventDef_fk'
    )
    BEGIN
        ALTER TABLE lds.[Event]
        DROP CONSTRAINT [EventEventDef_fk]
    END
    """)
    op.create_foreign_key('EventMethod_fk', 'Event', 'Method', ['MethodID'], ['ID'], source_schema='lds', referent_schema='lds')
    op.create_foreign_key('EventEventDef_fk', 'Event', 'EventDef', ['EventDefID'], ['ID'], source_schema='lds', referent_schema='lds')
    op.alter_column('Method', 'ID',
               existing_type=sa.INTEGER(),
               existing_nullable=False,
               schema='lds')
    op.alter_column('MethodDef', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.alter_column('MethodParam', 'Value',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.create_index(op.f('ix_lds_MethodParamDef_MethodDefID'), 'MethodParamDef', ['MethodDefID'], unique=False, schema='lds')
    op.create_foreign_key('MethodParamDefMethodDef_fk', 'MethodParamDef', 'MethodDef', ['MethodDefID'], ['ID'], source_schema='lds', referent_schema='lds')
    op.execute("""
    IF EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE name = 'SimulationParam_SimulationParamDef_fk'
    )
    BEGIN
        ALTER TABLE lds.[SimulationParam]
        DROP CONSTRAINT [SimulationParam_SimulationParamDef_fk]
    END
    """)
    op.execute("""
    DECLARE @fk_name NVARCHAR(255);

    SELECT @fk_name = fk.name
    FROM sys.foreign_keys fk
    JOIN sys.foreign_key_columns fkc
        ON fk.object_id = fkc.constraint_object_id
    JOIN sys.tables t
        ON fk.parent_object_id = t.object_id
    JOIN sys.schemas s
        ON t.schema_id = s.schema_id
    JOIN sys.columns c
        ON fkc.parent_object_id = c.object_id
       AND fkc.parent_column_id = c.column_id
    WHERE s.name = 'lds'
      AND t.name = 'SimulationParam'
      AND c.name = 'SimulationParamDefID';

    IF @fk_name IS NOT NULL
    BEGIN
        EXEC('ALTER TABLE lds.SimulationParam DROP CONSTRAINT ' + @fk_name)
    END
    """)
    op.drop_column('SimulationParam', 'SimulationDefID', schema='lds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SimulationParam', sa.Column('SimulationDefID', sa.CHAR(length=20, collation='SQL_Polish_CP1250_CS_AS', ), nullable=True), schema='lds')
    op.execute("""
    DELETE sp
    FROM lds.SimulationParam sp
    LEFT JOIN lds.SimulationParamDef spd
        ON sp.SimulationParamDefID = spd.ID
       AND sp.SimulationDefID = spd.SimulationDefID
    WHERE spd.ID IS NULL
    """)
    op.alter_column(
        'SimulationParam',
        'SimulationDefID',
        existing_type=sa.CHAR(length=20, collation='SQL_Polish_CP1250_CS_AS', ),
        nullable=False,
        schema='lds'
    )
    op.create_foreign_key('SimulationParamSimulationParamDef_fk', 'SimulationParam', 'SimulationParamDef', ['SimulationParamDefID', 'SimulationDefID'], ['ID', 'SimulationDefID'], source_schema='lds', referent_schema='lds')
    op.drop_constraint('MethodParamDefMethodDef_fk', 'MethodParamDef', schema='lds', type_='foreignkey')
    op.drop_index(op.f('ix_lds_MethodParamDef_MethodDefID'), table_name='MethodParamDef', schema='lds')
    op.alter_column('MethodParam', 'Value',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.alter_column('MethodDef', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.alter_column('Method', 'ID',
               existing_type=sa.INTEGER(),
               existing_nullable=False,
               schema='lds')
    op.drop_constraint('EventMethod_fk', 'Event', schema='lds', type_='foreignkey')
    op.drop_constraint('EventEventDef_fk', 'Event', schema='lds', type_='foreignkey')
    op.execute("""
    IF NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE name = 'Event_EventDef_fk'
    )
    BEGIN
        ALTER TABLE lds.[SimulationParam]
        DROP CONSTRAINT [SimulationParam_SimulationParamDef_fk]
    END
    """)
    op.execute("""
    IF NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE name = 'Event_EventDef_fk'
          AND parent_object_id = OBJECT_ID('lds.Event')
    )
    BEGIN
        ALTER TABLE lds.[Event]
        ADD CONSTRAINT [Event_EventDef_fk]
        FOREIGN KEY ([EventDefID])
        REFERENCES lds.[EventDef] ([ID])
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
    END
    """)
    op.execute("""
    IF NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE name = 'Event_Method_fk'
          AND parent_object_id = OBJECT_ID('lds.Event')
    )
    BEGIN
        ALTER TABLE lds.[Event]
        ADD CONSTRAINT [Event_Method_fk]
        FOREIGN KEY ([MethodID])
        REFERENCES lds.[Method] ([ID])
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
    END
    """)
    op.create_table('PipelineNode',
    sa.Column('PipelineID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('NodeID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('First', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['NodeID'], ['lds.Node.ID'], name='PipelineNodeNode_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PipelineID'], ['lds.Pipeline.ID'], name='PipelineNodePipeline_fk', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PipelineID', 'NodeID', name='PipelineNode_pk'),
    schema='lds'
    )
    # ### end Alembic commands ###
