"""Simulation tables created

Revision ID: 33c046bfd4f2
Revises: ad765074da32
Create Date: 2025-06-26 22:03:44.504497

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '33c046bfd4f2'
down_revision: Union[str, None] = 'ad765074da32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SimulationDef',
    sa.Column('ID', sa.CHAR(length=20, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('SimulationParamDef',
    sa.Column('ID', sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('SimulationDefID', sa.CHAR(length=20, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('DataType', sa.VARCHAR(length=20, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.ForeignKeyConstraint(['SimulationDefID'], ['lds.SimulationDef.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID', 'SimulationDefID', name='SimulationParamDef_pk'),
    schema='lds'
    )
    op.create_table('Simulation',
    sa.Column('SimulationDefID', sa.CHAR(length=20, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('TrendID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('RefreshTimeSeconds', sa.Integer(), nullable=False),
    sa.Column('DistanceMeters', sa.Integer(), nullable=False),
    sa.Column('ID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.ForeignKeyConstraint(['SimulationDefID'], ['lds.SimulationDef.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['TrendID'], ['lds.Trend.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('SimulationData',
    sa.Column('Distance', sa.Integer(), nullable=False),
    sa.Column('Data', sa.Integer(), nullable=True),
    sa.Column('SimulationID', sa.Integer(), nullable=False),
    sa.Column('Time', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['SimulationID'], ['lds.Simulation.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('SimulationID', 'Distance', name='SimulationData_pk'),
    schema='lds'
    )
    op.create_table('SimulationParam',
    sa.Column('SimulationID', sa.Integer(), nullable=False),
    sa.Column('SimulationParamDefID', sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Value', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('SimulationDefID', sa.CHAR(length=20, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.ForeignKeyConstraint(['SimulationID'], ['lds.Simulation.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['SimulationParamDefID', 'SimulationDefID'], ['lds.SimulationParamDef.ID', 'lds.SimulationParamDef.SimulationDefID'], onupdate='NO ACTION', ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('SimulationID', 'SimulationParamDefID', name='SimulationParam_pk'),
    schema='lds'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SimulationParam', schema='lds')
    op.drop_table('SimulationData', schema='lds')
    op.drop_table('Simulation', schema='lds')
    op.drop_table('SimulationParamDef', schema='lds')
    op.drop_table('SimulationDef', schema='lds')
    # ### end Alembic commands ###
