"""Method Data table created

Revision ID: 54f295c48dbd
Revises: a97218791680
Create Date: 2026-01-08 11:01:49.050445

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '54f295c48dbd'
down_revision: Union[str, None] = 'a97218791680'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MethodData',
    sa.Column('MethodID', sa.Integer(), nullable=False),
    sa.Column('Position', sa.Integer(), nullable=False),
    sa.Column('Time', sa.BigInteger(), nullable=False),
    sa.Column('Value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['MethodID'], ['lds.Method.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MethodID', 'Position', 'Time', name='MethodData_pk'),
    schema='lds'
    )
    op.alter_column('Pipeline', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.drop_column('Pipeline', 'BeginPos', schema='lds')
    op.alter_column('PipelineParam', 'Value',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.drop_constraint('PipelineParamPipelineParamDef_fk', 'PipelineParam', schema='lds', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('PipelineParamPipelineParamDef_fk', 'PipelineParam', 'PipelineParamDef', ['PipelineParamDefID'], ['ID'], source_schema='lds', referent_schema='lds', onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('PipelineParam', 'Value',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.add_column('Pipeline', sa.Column('BeginPos', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True), schema='lds')
    op.alter_column('Pipeline', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.drop_table('MethodData', schema='lds')
    # ### end Alembic commands ###
