"""Simulation tables changes

Revision ID: 5a77d4e34577
Revises: 33c046bfd4f2
Create Date: 2025-07-07 22:19:08.631316

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5a77d4e34577'
down_revision: Union[str, None] = '33c046bfd4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE lds.SimulationData DROP CONSTRAINT SimulationData_pk")
    op.add_column('Simulation', sa.Column('ResolutionMeters', sa.Integer(), nullable=False), schema='lds')
    op.drop_column('Simulation', 'DistanceMeters', schema='lds')
    op.alter_column('SimulationData', 'Distance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False,
               schema='lds')
    op.execute("""
               ALTER TABLE lds.SimulationData
                   ADD CONSTRAINT SimulationData_pk PRIMARY KEY (SimulationID, Distance)
               """)
    op.execute("update lds.Unit set Symbol = 'kg_s' where lds.Unit.ID = 'kg/s'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE lds.SimulationData DROP CONSTRAINT SimulationData_pk")
    op.alter_column('SimulationData', 'Distance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='lds')
    op.add_column('Simulation', sa.Column('DistanceMeters', sa.INTEGER(), autoincrement=False, nullable=False), schema='lds')
    op.drop_column('Simulation', 'ResolutionMeters', schema='lds')
    op.execute("""
               ALTER TABLE lds.SimulationData
                   ADD CONSTRAINT SimulationData_pk PRIMARY KEY (SimulationID, Distance)
               """)
    op.execute("update lds.Unit set Symbol = 'kg/s' where lds.Unit.ID = 'kg_s'")
    # ### end Alembic commands ###
