"""Template table created

Revision ID: 62173ad18479
Revises: 9e3eabe94c15
Create Date: 2025-05-14 14:46:05.043379

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '62173ad18479'
down_revision: Union[str, None] = '9e3eabe94c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Template',
    sa.Column('Name', sa.String(length=50, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Axes', sa.JSON(), nullable=True),
    sa.Column('ID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Template', schema='lds')
    # ### end Alembic commands ###
