"""SQLAlchemy to SQLModel models changes

Revision ID: 7895d9ee90c6
Revises: bc609f005f4a
Create Date: 2025-05-14 12:40:36.488748

"""
from typing import Sequence, Union
from alembic import op


revision: str = '7895d9ee90c6'
down_revision: Union[str, None] = 'bc609f005f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
    IF EXISTS (
        SELECT 1 FROM sys.foreign_keys 
        WHERE name = 'Event_Method_fk' AND parent_object_id = OBJECT_ID('lds.Event')
    )
    BEGIN
        ALTER TABLE lds.[Event] DROP CONSTRAINT [Event_Method_fk];
        ALTER TABLE lds.[Event] ADD CONSTRAINT [Event_Method_fk] 
        FOREIGN KEY([MethodID]) REFERENCES lds.[Method]([ID]) 
        ON DELETE CASCADE ON UPDATE CASCADE;
    END
    ''')
    op.execute('''
        IF EXISTS (
            SELECT 1 FROM sys.foreign_keys 
            WHERE name = 'Event_EventDef_fk' AND parent_object_id = OBJECT_ID('lds.Event')
        )
        BEGIN
            ALTER TABLE lds.[Event] DROP CONSTRAINT [Event_EventDef_fk];
            ALTER TABLE lds.[Event] ADD CONSTRAINT [Event_EventDef_fk] 
            FOREIGN KEY([EventDefID]) REFERENCES lds.[EventDef]([ID]) 
            ON DELETE CASCADE ON UPDATE CASCADE;
        END
        ''')
    op.execute('''
        IF EXISTS (
            SELECT 1 FROM sys.foreign_keys 
            WHERE name = 'MethodParamMethod_fk' AND parent_object_id = OBJECT_ID('lds.MethodParam')
        )
        BEGIN
            ALTER TABLE lds.[MethodParam] DROP CONSTRAINT [MethodParamMethod_fk];
            ALTER TABLE lds.[MethodParam] ADD CONSTRAINT [MethodParamMethod_fk] 
            FOREIGN KEY([MethodID]) REFERENCES lds.[MethodParamDef]([ID]) 
            ON DELETE CASCADE ON UPDATE CASCADE;
        END
        ''')
    op.execute("""
        IF EXISTS (
            SELECT 1 FROM sys.indexes 
            WHERE name = 'MethodParamDef_idx' 
              AND object_id = OBJECT_ID('lds.MethodParamDef')
        )
        BEGIN
            DROP INDEX MethodParamDef_idx ON lds.MethodParamDef;
        END
        """)
    op.execute("""
            IF EXISTS (
                SELECT 1 FROM sys.indexes 
                WHERE name = 'TrendParamDef_idx' 
                  AND object_id = OBJECT_ID('lds.TrendParamDef')
            )
            BEGIN
                DROP INDEX TrendParamDef_idx ON lds.TrendParamDef;
            END
            """)
    op.create_index(op.f('ix_lds_TrendParamDef_TrendDefID'), 'TrendParamDef', ['TrendDefID'], unique=False, schema='lds')
    op.execute("""
    IF NOT EXISTS (
        SELECT 1
        FROM sys.columns columns
        JOIN sys.objects objects ON columns.object_id = objects.object_id
        JOIN sys.schemas schemas ON objects.schema_id = schemas.schema_id
        WHERE objects.name = 'Trend'
          AND schemas.name = 'lds'
          AND columns.name = 'RawMin'
    )
    BEGIN
        ALTER TABLE lds.[Trend] ADD [RawMin] INTEGER NOT NULL DEFAULT 0;
    END
    """)
    op.execute("""
    IF NOT EXISTS (
        SELECT 1
        FROM sys.columns columns
        JOIN sys.objects objects ON columns.object_id = objects.object_id
        JOIN sys.schemas schemas ON objects.schema_id = schemas.schema_id
        WHERE objects.name = 'Trend'
          AND schemas.name = 'lds'
          AND columns.name = 'RawMax'
    )
    BEGIN
        ALTER TABLE lds.[Trend] ADD [RawMax] INTEGER NOT NULL DEFAULT 1;
    END
    """)
    op.execute("""
    IF NOT EXISTS (
        SELECT 1
        FROM sys.columns columns
        JOIN sys.objects objects ON columns.object_id = objects.object_id
        JOIN sys.schemas schemas ON objects.schema_id = schemas.schema_id
        WHERE objects.name = 'Trend'
          AND schemas.name = 'lds'
          AND columns.name = 'ScaledMin'
    )
    BEGIN
        ALTER TABLE lds.[Trend] ADD [ScaledMin] FLOAT(53) NOT NULL DEFAULT 0.0;
    END
    """)
    op.execute("""
    IF NOT EXISTS (
        SELECT 1
        FROM sys.columns columns
        JOIN sys.objects objects ON columns.object_id = objects.object_id
        JOIN sys.schemas schemas ON objects.schema_id = schemas.schema_id
        WHERE objects.name = 'Trend'
          AND schemas.name = 'lds'
          AND columns.name = 'ScaledMax'
    )
    BEGIN
        ALTER TABLE lds.[Trend] ADD [ScaledMax] FLOAT(53) NOT NULL DEFAULT 1.0;
    END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lds_TrendParamDef_TrendDefID'), table_name='TrendParamDef', schema='lds')
    op.create_index('TrendParamDef_idx', 'TrendParamDef', ['TrendDefID'], unique=False, schema='lds')
    op.execute("""
        IF EXISTS (
            SELECT 1 
            FROM sys.foreign_keys 
            WHERE name = 'Trend_TrendDef_fk' 
              AND parent_object_id = OBJECT_ID('lds.Trend')
        )
        BEGIN
            ALTER TABLE lds.[Trend] DROP CONSTRAINT [Trend_TrendDef_fk];
        END
        """)
    op.create_index('MethodParamDef_idx', 'MethodParamDef', ['ID'], unique=False, schema='lds')
    op.execute("""
            IF EXISTS (
                SELECT 1 
                FROM sys.foreign_keys 
                WHERE name = 'MethodParamMethod_fk' 
                  AND parent_object_id = OBJECT_ID('lds.MethodParam')
            )
            BEGIN
                ALTER TABLE lds.[MethodParam] DROP CONSTRAINT [MethodParamMethod_fk];
            END
            """)
    op.create_foreign_key('MethodParamMethod_fk', 'MethodParam', 'Method', ['MethodID'], ['ID'], source_schema='lds', referent_schema='lds')
    op.execute("""
                IF EXISTS (
                    SELECT 1 
                    FROM sys.foreign_keys 
                    WHERE name = 'Event_Method_fk' 
                      AND parent_object_id = OBJECT_ID('lds.Event')
                )
                BEGIN
                    ALTER TABLE lds.[Event] DROP CONSTRAINT [Event_Method_fk];
                END
                """)
    op.execute("""
                    IF EXISTS (
                        SELECT 1 
                        FROM sys.foreign_keys 
                        WHERE name = 'Event_EventDef_fk' 
                          AND parent_object_id = OBJECT_ID('lds.Event')
                    )
                    BEGIN
                        ALTER TABLE lds.[Event] DROP CONSTRAINT [Event_EventDef_fk];
                    END
                    """)
    op.create_foreign_key('Event_EventDef_fk', 'Event', 'EventDef', ['EventDefID'], ['ID'], source_schema='lds', referent_schema='lds')
    op.create_foreign_key('Event_Method_fk', 'Event', 'Method', ['MethodID'], ['ID'], source_schema='lds', referent_schema='lds')
    # ### end Alembic commands ###
