"""SQLAlchemy to SQLModel models changes

Revision ID: 7895d9ee90c6
Revises: bc609f005f4a
Create Date: 2025-05-14 12:40:36.488748

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7895d9ee90c6'
down_revision: Union[str, None] = 'bc609f005f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Event_Method_fk', 'Event', schema='lds', type_='foreignkey')
    op.drop_constraint('Event_EventDef_fk', 'Event', schema='lds', type_='foreignkey')
    op.create_foreign_key('Event_EventDef_fk', 'Event', 'EventDef', ['EventDefID'], ['ID'], source_schema='lds', referent_schema='lds', onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('Event_Method_fk', 'Event', 'Method', ['MethodID'], ['ID'], source_schema='lds', referent_schema='lds', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('MethodParamMethod_fk', 'MethodParam', schema='lds', type_='foreignkey')
    op.create_foreign_key('MethodParam_Method_fk', 'MethodParam', 'Method', ['MethodID'], ['ID'], source_schema='lds', referent_schema='lds', onupdate='CASCADE', ondelete='CASCADE')
    op.drop_index('MethodParamDef_idx', table_name='MethodParamDef', schema='lds')
    op.alter_column('Trend', 'TrendDefID',
               existing_type=sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               type_=sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'),
               existing_nullable=False,
               schema='lds')
    op.create_foreign_key('Trend_TrendDef_fk', 'Trend', 'TrendDef', ['TrendDefID'], ['ID'], source_schema='lds', referent_schema='lds', ondelete='CASCADE')
    op.drop_index('TrendParamDef_idx', table_name='TrendParamDef', schema='lds')
    op.create_index(op.f('ix_lds_TrendParamDef_TrendDefID'), 'TrendParamDef', ['TrendDefID'], unique=False, schema='lds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lds_TrendParamDef_TrendDefID'), table_name='TrendParamDef', schema='lds')
    op.create_index('TrendParamDef_idx', 'TrendParamDef', ['TrendDefID'], unique=False, schema='lds')
    op.drop_constraint('Trend_TrendDef_fk', 'Trend', schema='lds', type_='foreignkey')
    op.alter_column('Trend', 'TrendDefID',
               existing_type=sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'),
               type_=sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               existing_nullable=False,
               schema='lds')
    op.create_index('MethodParamDef_idx', 'MethodParamDef', ['ID'], unique=False, schema='lds')
    op.drop_constraint('MethodParam_Method_fk', 'MethodParam', schema='lds', type_='foreignkey')
    op.create_foreign_key('MethodParamMethod_fk', 'MethodParam', 'Method', ['MethodID'], ['ID'], source_schema='lds', referent_schema='lds')
    op.drop_constraint('Event_Method_fk', 'Event', schema='lds', type_='foreignkey')
    op.drop_constraint('Event_EventDef_fk', 'Event', schema='lds', type_='foreignkey')
    op.create_foreign_key('Event_EventDef_fk', 'Event', 'EventDef', ['EventDefID'], ['ID'], source_schema='lds', referent_schema='lds')
    op.create_foreign_key('Event_Method_fk', 'Event', 'Method', ['MethodID'], ['ID'], source_schema='lds', referent_schema='lds')
    # ### end Alembic commands ###
