"""Trend color field type change

Revision ID: 9e3eabe94c15
Revises: 7895d9ee90c6
Create Date: 2025-05-14 13:51:38.327859

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9e3eabe94c15'
down_revision: Union[str, None] = '7895d9ee90c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Trend', 'Color',
               existing_type=sa.SMALLINT(),
               type_=sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               existing_nullable=True,
               schema='lds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Trend', 'Color',
               existing_type=sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               type_=sa.SMALLINT(),
               existing_nullable=True,
               schema='lds')
    # ### end Alembic commands ###
