"""Past Trend Data table

Revision ID: a97218791680
Revises: e7b6743541cc
Create Date: 2025-11-04 12:47:23.586070

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a97218791680'
down_revision: Union[str, None] = 'e7b6743541cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PastTrendData',
    sa.Column('TrendID', sa.Integer(), nullable=False),
    sa.Column('Time', sa.BigInteger(), nullable=False),
    sa.Column('Data', sa.BINARY(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Time', 'TrendID', name='PastTrendData_pk'),
    schema='lds'
    )
    op.create_index('past_idx_time_trendid', 'PastTrendData', ['TrendID', 'Time'], unique=True, schema='lds')
    op.execute("""
               CREATE PROCEDURE Update_Insert_PastTrendData @trend_id INT,
                                                            @time BIGINT,
                                                            @value BINARY(200)
               AS
               BEGIN
                   UPDATE lds.PastTrendData
                   SET Data = @value
                   WHERE TrendID = @trend_id
                     AND Time = @time;

                   IF @@ROWCOUNT = 0
                       BEGIN
                           INSERT INTO lds.PastTrendData (TrendID, Time, Data)
                           VALUES (@trend_id, @time, @value);
                       END
               END
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP PROCEDURE Update_Insert_PastTrendData")
    op.drop_index('past_idx_time_trendid', table_name='PastTrendData', schema='lds')
    op.drop_table('PastTrendData', schema='lds')
    # ### end Alembic commands ###
