"""Profiler data stored in database

Revision ID: ad765074da32
Revises: f32d58e87ffb
Create Date: 2025-06-17 11:12:10.747746

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ad765074da32'
down_revision: Union[str, None] = 'f32d58e87ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProfilerData',
    sa.Column('ID', sa.Integer(), nullable=True),
    sa.Column('Time10', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('Time100', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('Time1000', sa.DECIMAL(precision=10, scale=5), nullable=True),
    sa.Column('QueueSize', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ID'], ['lds.Trend.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_foreign_key('Trend_TrendGroup_fk', 'Trend', 'TrendGroup', ['TrendGroupID'], ['ID'], source_schema='lds', referent_schema='lds', onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Trend_TrendGroup_fk', 'Trend', schema='lds', type_='foreignkey')
    op.drop_table('ProfilerData', schema='lds')
    # ### end Alembic commands ###
