"""Initial revision

Revision ID: bc609f005f4a
Revises: 
Create Date: 2025-05-14 11:07:20.259929

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'bc609f005f4a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EventDef',
    sa.Column('Verbosity', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Caption', sa.CHAR(length=60, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Silent', sa.Boolean(), nullable=False),
    sa.Column('Visible', sa.Boolean(), nullable=False),
    sa.Column('Enabled', sa.Boolean(), nullable=False),
    sa.Column('ID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('MethodDef',
    sa.Column('ID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('MethodParamDef',
    sa.Column('ID', sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('MethodDefID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('DataType', sa.CHAR(length=6, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('Node',
    sa.Column('Type', sa.CHAR(length=6, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Name', sa.String(length=50, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('ID', sa.Integer(), sa.Identity(always=False, start=1000, increment=1), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('Pipeline',
    sa.Column('ID', sa.Integer(), sa.Identity(always=False, start=2, increment=1), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('BeginPos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('PipelineParamDef',
    sa.Column('ID', sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('DataType', sa.CHAR(length=6, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('TrendData',
    sa.Column('TrendID', sa.Integer(), nullable=False),
    sa.Column('Time', sa.BigInteger(), nullable=False),
    sa.Column('Data', sa.BINARY(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Time', 'TrendID', name='TrendData_pk'),
    schema='lds'
    )
    op.create_table('TrendDef',
    sa.Column('ID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('TrendGroup',
    sa.Column('ID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.Column('Name', sa.String(length=100, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('AnalisisOnly', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('Unit',
    sa.Column('ID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('Symbol', sa.String(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('BaseID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('Multiplier', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('Node',
    sa.Column('PosX', sa.Integer(), nullable=True),
    sa.Column('PosY', sa.Integer(), nullable=True),
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID'], ['lds.Node.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    schema='editor'
    )
    op.create_table('Pipeline',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('AreaWidth', sa.Integer(), nullable=False),
    sa.Column('AreaWidthDivision', sa.Integer(), nullable=False),
    sa.Column('AreaHeight', sa.Integer(), nullable=False),
    sa.Column('AreaHeightDivision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID'], ['lds.Pipeline.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    schema='editor'
    )
    op.create_table('Link',
    sa.Column('BeginNodeID', sa.Integer(), nullable=True),
    sa.Column('EndNodeID', sa.Integer(), nullable=True),
    sa.Column('Length', sa.Float(), nullable=True),
    sa.Column('ID', sa.Integer(), sa.Identity(always=False, start=1, increment=1), nullable=False),
    sa.ForeignKeyConstraint(['BeginNodeID'], ['lds.Node.ID'], ),
    sa.ForeignKeyConstraint(['EndNodeID'], ['lds.Node.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('Method',
    sa.Column('ID', sa.Integer(), sa.Identity(always=False, start=1000, increment=1), nullable=False),
    sa.Column('MethodDefID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('PipelineID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.ForeignKeyConstraint(['MethodDefID'], ['lds.MethodDef.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PipelineID'], ['lds.Pipeline.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('PipelineNode',
    sa.Column('PipelineID', sa.Integer(), nullable=False),
    sa.Column('NodeID', sa.Integer(), nullable=False),
    sa.Column('First', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['NodeID'], ['lds.Node.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['PipelineID'], ['lds.Pipeline.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PipelineID', 'NodeID', name='PipelineNode_pk'),
    schema='lds'
    )
    op.create_table('PipelineParam',
    sa.Column('PipelineParamDefID', sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('PipelineID', sa.Integer(), nullable=False),
    sa.Column('Value', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.ForeignKeyConstraint(['PipelineID'], ['lds.Pipeline.ID'], ),
    sa.ForeignKeyConstraint(['PipelineParamDefID'], ['lds.PipelineParamDef.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('PipelineParamDefID', 'PipelineID', name='PipelineParam_pk'),
    schema='lds'
    )
    op.create_table('Trend',
    sa.Column('ID', sa.Integer(), sa.Identity(always=False, start=1000, increment=1), nullable=False),
    sa.Column('TrendDefID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('RawMin', sa.Integer(), nullable=False),
    sa.Column('RawMax', sa.Integer(), nullable=False),
    sa.Column('ScaledMin', sa.Float(precision=53), nullable=False),
    sa.Column('ScaledMax', sa.Float(precision=53), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('TrendGroupID', sa.Integer(), nullable=True),
    sa.Column('TimeExponent', sa.Integer(), nullable=True),
    sa.Column('Format', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('UnitID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('Color', sa.SmallInteger(), nullable=True),
    sa.Column('Symbol', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('NodeID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['NodeID'], ['lds.Node.ID'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['TrendDefID'], ['lds.TrendDef.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['UnitID'], ['lds.Unit.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('TrendParamDef',
    sa.Column('ID', sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('TrendDefID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Name', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('DataType', sa.CHAR(length=6, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.ForeignKeyConstraint(['TrendDefID'], ['lds.TrendDef.ID'], ),
    sa.PrimaryKeyConstraint('ID', 'TrendDefID', name='TrendParamDef_pk'),
    schema='lds'
    )
    op.create_index(op.f('ix_lds_TrendParamDef_TrendDefID'), 'TrendParamDef', ['TrendDefID'], unique=False, schema='lds')
    op.create_table('Event',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EventDefID', sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('MethodID', sa.Integer(), nullable=False),
    sa.Column('BeginDate', sa.DateTime(), nullable=False),
    sa.Column('AckDate', sa.DateTime(), nullable=True),
    sa.Column('EndDate', sa.DateTime(), nullable=True),
    sa.Column('Details', sa.String(length=100, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.Column('Position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['EventDefID'], ['lds.EventDef.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['MethodID'], ['lds.Method.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID'),
    schema='lds'
    )
    op.create_table('MethodParam',
    sa.Column('MethodParamDefID', sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('MethodID', sa.Integer(), nullable=False),
    sa.Column('Value', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.ForeignKeyConstraint(['MethodID'], ['lds.Method.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('MethodParamDefID'),
    schema='lds'
    )
    op.create_table('TrendParam',
    sa.Column('TrendID', sa.Integer(), nullable=False),
    sa.Column('TrendParamDefID', sa.CHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=False),
    sa.Column('Value', sa.String(length=30, collation='SQL_Polish_CP1250_CS_AS'), nullable=True),
    sa.ForeignKeyConstraint(['TrendID'], ['lds.Trend.ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('TrendParamDefID', 'TrendID', name='TrendParam_pk'),
    schema='lds'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrendParam', schema='lds')
    op.drop_table('MethodParam', schema='lds')
    op.drop_table('Event', schema='lds')
    op.drop_index(op.f('ix_lds_TrendParamDef_TrendDefID'), table_name='TrendParamDef', schema='lds')
    op.drop_table('TrendParamDef', schema='lds')
    op.drop_table('Trend', schema='lds')
    op.drop_table('PipelineParam', schema='lds')
    op.drop_table('PipelineNode', schema='lds')
    op.drop_table('Method', schema='lds')
    op.drop_table('Link', schema='lds')
    op.drop_table('Pipeline', schema='editor')
    op.drop_table('Node', schema='editor')
    op.drop_table('Unit', schema='lds')
    op.drop_table('TrendGroup', schema='lds')
    op.drop_table('TrendDef', schema='lds')
    op.drop_table('TrendData', schema='lds')
    op.drop_table('PipelineParamDef', schema='lds')
    op.drop_table('Pipeline', schema='lds')
    op.drop_table('Node', schema='lds')
    op.drop_table('MethodParamDef', schema='lds')
    op.drop_table('MethodDef', schema='lds')
    op.drop_table('EventDef', schema='lds')
    # ### end Alembic commands ###
