"""Enabled flags in trend and simulation

Revision ID: e7b6743541cc
Revises: fc42915e439c
Create Date: 2025-09-12 11:40:46.949003

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e7b6743541cc'
down_revision: Union[str, None] = 'fc42915e439c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('EventDef', 'Caption',
               existing_type=sa.CHAR(length=60, collation='SQL_Polish_CP1250_CS_AS'),
               type_=sa.VARCHAR(length=60, collation='SQL_Polish_CP1250_CS_AS'),
               existing_nullable=False,
               schema='lds')

    op.add_column('Simulation', sa.Column('Enabled', sa.Boolean(), nullable=True),
                  schema='lds')
    op.execute("UPDATE lds.[Simulation] SET Enabled = 1 WHERE Enabled IS NULL")
    op.alter_column(
        'Simulation',
        'Enabled',
        existing_type=sa.Boolean(),
        nullable=False,
        schema='lds'
    )

    op.add_column('Trend', sa.Column('Enabled', sa.Boolean(), nullable=True),
                  schema='lds')
    op.execute("UPDATE lds.[Trend] SET Enabled = 1 WHERE Enabled IS NULL")
    op.alter_column(
        'Trend',
        'Enabled',
        existing_type=sa.Boolean(),
        nullable=False,
        schema='lds'
    )

    op.execute("UPDATE lds.[Unit] SET Multiplier = 1.0 WHERE Multiplier IS NULL")
    op.alter_column('Unit',
                    'Multiplier',
                    existing_type=sa.NUMERIC(precision=20, scale=10),
                    nullable=False,
                    schema='lds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Unit', 'Multiplier',
               existing_type=sa.NUMERIC(precision=20, scale=10),
               nullable=True,
               schema='lds')
    op.drop_column('Trend', 'Enabled', schema='lds')
    op.drop_column('Simulation', 'Enabled', schema='lds')
    op.alter_column('EventDef', 'Caption',
               existing_type=sa.VARCHAR(length=60, collation='SQL_Polish_CP1250_CS_AS'),
               type_=sa.CHAR(length=60, collation='SQL_Polish_CP1250_CS_AS'),
               existing_nullable=False,
               schema='lds')
    # ### end Alembic commands ###
