"""TrendData index and procedure

Revision ID: f32d58e87ffb
Revises: 62173ad18479
Create Date: 2025-06-10 11:15:23.155388

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

revision: str = 'f32d58e87ffb'
down_revision: Union[str, None] = '62173ad18479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f"""
        IF EXISTS (SELECT 1 
                   FROM sys.indexes 
                   WHERE name = 'idx_time_trendid' 
                     AND object_id = OBJECT_ID('lds.TrendData'))
        DROP INDEX idx_time_trendid ON lds.TrendData;
    """)
    op.create_index('idx_time_trendid', 'TrendData', ['TrendID', 'Time'], unique=True, schema='lds')
    op.add_column('TrendGroup', sa.Column('AnalysisOnly', sa.Boolean(), server_default='0', nullable=False), schema='lds')
    op.execute(f"""
        DECLARE @ConstraintName NVARCHAR(200)
        SELECT @ConstraintName = dc.name
        FROM sys.default_constraints dc
        INNER JOIN sys.columns c ON c.object_id = dc.parent_object_id AND c.column_id = dc.parent_column_id
        WHERE OBJECT_NAME(dc.parent_object_id) = 'TrendGroup'
          AND c.name = 'AnalisisOnly'
          AND SCHEMA_NAME(dc.schema_id) = 'lds';

        IF @ConstraintName IS NOT NULL
        BEGIN
            EXEC('ALTER TABLE [lds].[TrendGroup] DROP CONSTRAINT [' + @ConstraintName + ']')
        END
        """)
    op.drop_column('TrendGroup', 'AnalisisOnly', schema='lds')
    op.execute("""
                CREATE PROCEDURE Update_Insert_TrendData
                    @trend_id INT,
                    @time BIGINT,
                    @value BINARY(200)
                    AS
                    BEGIN
                        UPDATE lds.TrendData
                        SET Data = @value
                        WHERE TrendID = @trend_id AND Time = @time;
                    
                        IF @@ROWCOUNT = 0
                        BEGIN
                            INSERT INTO lds.TrendData (TrendID, Time, Data)
                            VALUES (@trend_id, @time, @value);
                        END
                    END
               """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TrendGroup', sa.Column('AnalisisOnly', mssql.BIT(), server_default=sa.text('((0))'), autoincrement=False, nullable=False), schema='lds')
    op.execute(f"""
            DECLARE @ConstraintName NVARCHAR(200)
            SELECT @ConstraintName = dc.name
            FROM sys.default_constraints dc
            INNER JOIN sys.columns c ON c.object_id = dc.parent_object_id AND c.column_id = dc.parent_column_id
            WHERE OBJECT_NAME(dc.parent_object_id) = 'TrendGroup'
              AND c.name = 'AnalysisOnly'
              AND SCHEMA_NAME(dc.schema_id) = 'lds';

            IF @ConstraintName IS NOT NULL
            BEGIN
                EXEC('ALTER TABLE [lds].[TrendGroup] DROP CONSTRAINT [' + @ConstraintName + ']')
            END
            """)
    op.drop_column('TrendGroup', 'AnalysisOnly', schema='lds')
    op.execute(f"""
            IF EXISTS (SELECT 1 
                       FROM sys.indexes 
                       WHERE name = 'idx_time_trendid' 
                         AND object_id = OBJECT_ID('lds.TrendData'))
            DROP INDEX idx_time_trendid ON lds.TrendData;
        """)
    op.create_index('idx_time_trendid', 'TrendData', ['Time', 'TrendID'], unique=False, schema='lds')
    op.execute("DROP PROCEDURE Update_Insert_TrendData")
    # ### end Alembic commands ###
