"""Change to fields nullable possibility

Revision ID: fc42915e439c
Revises: 0da9a491388c
Create Date: 2025-08-21 13:45:04.559336

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fc42915e439c'
down_revision: Union[str, None] = '0da9a491388c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
    IF EXISTS (
        SELECT 1
        FROM sys.columns c
        JOIN sys.objects o ON c.object_id = o.object_id
        JOIN sys.schemas s ON o.schema_id = s.schema_id
        JOIN sys.types t ON c.system_type_id = t.user_type_id
        WHERE o.name = 'Event' 
          AND s.name = 'lds'
          AND c.name = 'ID'
		  AND t.name = 'bigint'
    )
    BEGIN
        ALTER TABLE lds.[Event] DROP CONSTRAINT [PK_Event]
        ALTER TABLE lds.[Event] 
        ALTER COLUMN [ID] INT NOT NULL
        ALTER TABLE lds.[Event] ADD CONSTRAINT [PK_Event] PRIMARY KEY CLUSTERED ([ID])
    END
    """)
    op.execute('update lds.Simulation set Name = \'default name\' where Name is null;')
    op.alter_column('Simulation', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.create_foreign_key('SimulationParam_SimulationParamDef_fk', 'SimulationParam', 'SimulationParamDef', ['SimulationParamDefID', 'SimulationDefID'], ['ID', 'SimulationDefID'], source_schema='lds', referent_schema='lds', onupdate='NO ACTION', ondelete='NO ACTION')
    op.execute('update lds.Trend set Name = \'default name\' where Name is null;')
    op.alter_column('Trend', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.execute('''
    IF NOT EXISTS (SELECT * FROM lds.TrendGroup)
	INSERT INTO lds.TrendGroup (Name) VALUES ('DefaultGroup');
	''')
    op.execute('''
    DECLARE @DefaultTrendGroupID INT;
    SELECT TOP 1 @DefaultTrendGroupID = ID FROM lds.TrendGroup;
    update lds.Trend set TrendGroupID = @DefaultTrendGroupID where TrendGroupID is null;
    ''')
    op.alter_column('Trend', 'TrendGroupID',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='lds')
    op.execute('''
        IF NOT EXISTS (SELECT * FROM lds.Unit)
        insert into lds.Unit (ID, Name, Symbol) VALUES ('DefUnit', 'default name', 'symbol');
    	''')
    op.execute('''
        DECLARE @DefaultUnitID CHAR(10);
        SELECT TOP 1 @DefaultUnitID = ID FROM lds.Unit;
        update lds.Trend set UnitID = @DefaultUnitID where UnitID is null;
        ''')
    op.alter_column('Trend', 'UnitID',
               existing_type=sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.execute('update lds.Trend set Color = \'default color\' where Color is null;')
    op.alter_column('Trend', 'Color',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.execute('update lds.TrendDef set Name = \'default name\' where Name is null;')
    op.alter_column('TrendDef', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.execute('update lds.Unit set Name = \'default name\' where Name is null;')
    op.alter_column('Unit', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.execute('update lds.Unit set Symbol = \'symbol\' where Symbol is null;')
    op.alter_column('Unit', 'Symbol',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=False,
               schema='lds')
    op.execute('DELETE FROM lds.TrendParam WHERE TrendParamDefID is null;')
    op.execute('''
    delete from lds.TrendParam 
    where TrendParamDefID in ('SCALED_MIN', 'SCALED_MAX', 'RAW_MIN', 'RAW_MAX');
    
    delete from lds.TrendParamDef 
    where ID in ('SCALED_MIN', 'SCALED_MAX', 'RAW_MIN', 'RAW_MAX');
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Unit', 'Symbol',
               existing_type=sa.VARCHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.alter_column('Unit', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.alter_column('TrendDef', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.alter_column('Trend', 'Color',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.alter_column('Trend', 'UnitID',
               existing_type=sa.CHAR(length=10, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.alter_column('Trend', 'TrendGroupID',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='lds')
    op.alter_column('Trend', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    op.drop_constraint('SimulationParam_SimulationParamDef_fk', 'SimulationParam', schema='lds', type_='foreignkey')
    op.alter_column('Simulation', 'Name',
               existing_type=sa.VARCHAR(length=30, collation='SQL_Polish_CP1250_CS_AS'),
               nullable=True,
               schema='lds')
    # ### end Alembic commands ###
