// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    Information,
    InformationFromJSON,
    InformationToJSON,
    Method,
    MethodFromJSON,
    MethodToJSON,
    MethodParam,
    MethodParamFromJSON,
    MethodParamToJSON,
} from '../models';

export interface CreateMethodRequest {
    pipelineId: number;
    method?: Method;
}

export interface DeleteMethodByIdRequest {
    pipelineId: number;
    methodId: number;
}

export interface GetMethodByIdRequest {
    pipelineId: number;
    methodId: number;
}

export interface ListMethodParamsRequest {
    pipelineId: number;
    methodId: number;
}

export interface ListMethodsRequest {
    pipelineId: number;
}

export interface UpdateMethodRequest {
    pipelineId: number;
    methodId: number;
    method?: Method;
}

export interface UpdateMethodParamRequest {
    pipelineId: number;
    methodId: number;
    methodParamDefId: string;
    methodParam?: Array<MethodParam>;
}


/**
 * Creates a  method
 * Creates method
 */
function createMethodRaw<T>(requestParameters: CreateMethodRequest, requestConfig: runtime.TypedQueryConfig<T, Method> = {}): QueryConfig<T> {
    if (requestParameters.pipelineId === null || requestParameters.pipelineId === undefined) {
        throw new runtime.RequiredError('pipelineId','Required parameter requestParameters.pipelineId was null or undefined when calling createMethod.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/pipeline/{pipelineId}/method`.replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters.pipelineId))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'POST',
            headers: headerParameters,
        },
        body: queryParameters || MethodToJSON(requestParameters.method),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(MethodFromJSON(body), text);
    }

    return config;
}

/**
* Creates a  method
* Creates method
*/
export function createMethod<T>(requestParameters: CreateMethodRequest, requestConfig?: runtime.TypedQueryConfig<T, Method>): QueryConfig<T> {
    return createMethodRaw(requestParameters, requestConfig);
}

/**
 * Deletes specific  method
 * Deletes  method
 */
function deleteMethodByIdRaw<T>(requestParameters: DeleteMethodByIdRequest, requestConfig: runtime.TypedQueryConfig<T, Information> = {}): QueryConfig<T> {
    if (requestParameters.pipelineId === null || requestParameters.pipelineId === undefined) {
        throw new runtime.RequiredError('pipelineId','Required parameter requestParameters.pipelineId was null or undefined when calling deleteMethodById.');
    }

    if (requestParameters.methodId === null || requestParameters.methodId === undefined) {
        throw new runtime.RequiredError('methodId','Required parameter requestParameters.methodId was null or undefined when calling deleteMethodById.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/pipeline/{pipelineId}/method/{methodId}`.replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters.pipelineId))).replace(`{${"methodId"}}`, encodeURIComponent(String(requestParameters.methodId))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'DELETE',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(InformationFromJSON(body), text);
    }

    return config;
}

/**
* Deletes specific  method
* Deletes  method
*/
export function deleteMethodById<T>(requestParameters: DeleteMethodByIdRequest, requestConfig?: runtime.TypedQueryConfig<T, Information>): QueryConfig<T> {
    return deleteMethodByIdRaw(requestParameters, requestConfig);
}

/**
 * Info for specific  method
 * Gets  method details
 */
function getMethodByIdRaw<T>(requestParameters: GetMethodByIdRequest, requestConfig: runtime.TypedQueryConfig<T, Method> = {}): QueryConfig<T> {
    if (requestParameters.pipelineId === null || requestParameters.pipelineId === undefined) {
        throw new runtime.RequiredError('pipelineId','Required parameter requestParameters.pipelineId was null or undefined when calling getMethodById.');
    }

    if (requestParameters.methodId === null || requestParameters.methodId === undefined) {
        throw new runtime.RequiredError('methodId','Required parameter requestParameters.methodId was null or undefined when calling getMethodById.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/pipeline/{pipelineId}/method/{methodId}`.replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters.pipelineId))).replace(`{${"methodId"}}`, encodeURIComponent(String(requestParameters.methodId))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(MethodFromJSON(body), text);
    }

    return config;
}

/**
* Info for specific  method
* Gets  method details
*/
export function getMethodById<T>(requestParameters: GetMethodByIdRequest, requestConfig?: runtime.TypedQueryConfig<T, Method>): QueryConfig<T> {
    return getMethodByIdRaw(requestParameters, requestConfig);
}

/**
 * List all  method params
 * List pipelnie method params
 */
function listMethodParamsRaw<T>(requestParameters: ListMethodParamsRequest, requestConfig: runtime.TypedQueryConfig<T, Array<MethodParam>> = {}): QueryConfig<T> {
    if (requestParameters.pipelineId === null || requestParameters.pipelineId === undefined) {
        throw new runtime.RequiredError('pipelineId','Required parameter requestParameters.pipelineId was null or undefined when calling listMethodParams.');
    }

    if (requestParameters.methodId === null || requestParameters.methodId === undefined) {
        throw new runtime.RequiredError('methodId','Required parameter requestParameters.methodId was null or undefined when calling listMethodParams.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/pipeline/{pipelineId}/method/{methodId}/param`.replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters.pipelineId))).replace(`{${"methodId"}}`, encodeURIComponent(String(requestParameters.methodId))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(body.map(MethodParamFromJSON), text);
    }

    return config;
}

/**
* List all  method params
* List pipelnie method params
*/
export function listMethodParams<T>(requestParameters: ListMethodParamsRequest, requestConfig?: runtime.TypedQueryConfig<T, Array<MethodParam>>): QueryConfig<T> {
    return listMethodParamsRaw(requestParameters, requestConfig);
}

/**
 * List all methods
 * List pipelnie methods
 */
function listMethodsRaw<T>(requestParameters: ListMethodsRequest, requestConfig: runtime.TypedQueryConfig<T, Array<Method>> = {}): QueryConfig<T> {
    if (requestParameters.pipelineId === null || requestParameters.pipelineId === undefined) {
        throw new runtime.RequiredError('pipelineId','Required parameter requestParameters.pipelineId was null or undefined when calling listMethods.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/pipeline/{pipelineId}/method`.replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters.pipelineId))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'GET',
            headers: headerParameters,
        },
        body: queryParameters,
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(body.map(MethodFromJSON), text);
    }

    return config;
}

/**
* List all methods
* List pipelnie methods
*/
export function listMethods<T>(requestParameters: ListMethodsRequest, requestConfig?: runtime.TypedQueryConfig<T, Array<Method>>): QueryConfig<T> {
    return listMethodsRaw(requestParameters, requestConfig);
}

/**
 * Updates  method
 * Updates method
 */
function updateMethodRaw<T>(requestParameters: UpdateMethodRequest, requestConfig: runtime.TypedQueryConfig<T, Method> = {}): QueryConfig<T> {
    if (requestParameters.pipelineId === null || requestParameters.pipelineId === undefined) {
        throw new runtime.RequiredError('pipelineId','Required parameter requestParameters.pipelineId was null or undefined when calling updateMethod.');
    }

    if (requestParameters.methodId === null || requestParameters.methodId === undefined) {
        throw new runtime.RequiredError('methodId','Required parameter requestParameters.methodId was null or undefined when calling updateMethod.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/pipeline/{pipelineId}/method/{methodId}`.replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters.pipelineId))).replace(`{${"methodId"}}`, encodeURIComponent(String(requestParameters.methodId))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'PUT',
            headers: headerParameters,
        },
        body: queryParameters || MethodToJSON(requestParameters.method),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(MethodFromJSON(body), text);
    }

    return config;
}

/**
* Updates  method
* Updates method
*/
export function updateMethod<T>(requestParameters: UpdateMethodRequest, requestConfig?: runtime.TypedQueryConfig<T, Method>): QueryConfig<T> {
    return updateMethodRaw(requestParameters, requestConfig);
}

/**
 * Put  method params
 * Put pipelnie method params
 */
function updateMethodParamRaw<T>(requestParameters: UpdateMethodParamRequest, requestConfig: runtime.TypedQueryConfig<T, Information> = {}): QueryConfig<T> {
    if (requestParameters.pipelineId === null || requestParameters.pipelineId === undefined) {
        throw new runtime.RequiredError('pipelineId','Required parameter requestParameters.pipelineId was null or undefined when calling updateMethodParam.');
    }

    if (requestParameters.methodId === null || requestParameters.methodId === undefined) {
        throw new runtime.RequiredError('methodId','Required parameter requestParameters.methodId was null or undefined when calling updateMethodParam.');
    }

    if (requestParameters.methodParamDefId === null || requestParameters.methodParamDefId === undefined) {
        throw new runtime.RequiredError('methodParamDefId','Required parameter requestParameters.methodParamDefId was null or undefined when calling updateMethodParam.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/pipeline/{pipelineId}/method/{methodId}/param/{methodParamDefId}`.replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters.pipelineId))).replace(`{${"methodId"}}`, encodeURIComponent(String(requestParameters.methodId))).replace(`{${"methodParamDefId"}}`, encodeURIComponent(String(requestParameters.methodParamDefId))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'PUT',
            headers: headerParameters,
        },
        body: queryParameters || requestParameters.methodParam?.map(MethodParamToJSON),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(InformationFromJSON(body), text);
    }

    return config;
}

/**
* Put  method params
* Put pipelnie method params
*/
export function updateMethodParam<T>(requestParameters: UpdateMethodParamRequest, requestConfig?: runtime.TypedQueryConfig<T, Information>): QueryConfig<T> {
    return updateMethodParamRaw(requestParameters, requestConfig);
}

