// tslint:disable
/**
 * Nefryt LDS API
 * Database API for Nefryt LDS
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { HttpMethods, QueryConfig, ResponseBody, ResponseText } from 'redux-query';
import * as runtime from '../runtime';
import {
    Information,
    InformationFromJSON,
    InformationToJSON,
    Method,
    MethodFromJSON,
    MethodToJSON,
} from '../models';

export interface UpdateMethodRequest {
    pipelineId: number;
    method?: Method;
}


/**
 * Updates  method
 * Updates method
 */
function updateMethodRaw<T>(requestParameters: UpdateMethodRequest, requestConfig: runtime.TypedQueryConfig<T, Information> = {}): QueryConfig<T> {
    if (requestParameters.pipelineId === null || requestParameters.pipelineId === undefined) {
        throw new runtime.RequiredError('pipelineId','Required parameter requestParameters.pipelineId was null or undefined when calling updateMethod.');
    }

    let queryParameters = null;


    const headerParameters : runtime.HttpHeaders = {};

    headerParameters['Content-Type'] = 'application/json';


    const { meta = {} } = requestConfig;

    const config: QueryConfig<T> = {
        url: `${runtime.Configuration.basePath}/pipeline/{pipelineId}/method`.replace(`{${"pipelineId"}}`, encodeURIComponent(String(requestParameters.pipelineId))),
        meta,
        update: requestConfig.update,
        queryKey: requestConfig.queryKey,
        optimisticUpdate: requestConfig.optimisticUpdate,
        force: requestConfig.force,
        rollback: requestConfig.rollback,
        options: {
            method: 'PUT',
            headers: headerParameters,
        },
        body: queryParameters || MethodToJSON(requestParameters.method),
    };

    const { transform: requestTransform } = requestConfig;
    if (requestTransform) {
        config.transform = (body: ResponseBody, text: ResponseBody) => requestTransform(InformationFromJSON(body), text);
    }

    return config;
}

/**
* Updates  method
* Updates method
*/
export function updateMethod<T>(requestParameters: UpdateMethodRequest, requestConfig?: runtime.TypedQueryConfig<T, Information>): QueryConfig<T> {
    return updateMethodRaw(requestParameters, requestConfig);
}

